### ISSUE TITLE
Enhancement request - assigning tags in bulk

### ISSUE THREAD

**Issue by paulmrozowski** [DougHennig/ProjectExplorer#10]
It would be really nice to be able to assign a tag / category "in bulk". So you could do something like set a filter to show only files that meet some criteria (for example, all start with "invoice_"), then assign them ALL the same tag. Right now you have to manually click on each item, click the tag dropdown, select the tag(s), close the dropdown, then click Save for each and every one.

**Comment by DougHennig** [comment]
Done in the latest commit. Choose Assign Tags for Items from the File menu to specify the tags to add and the filter condition for the items.
