### ISSUE TITLE
New position for Save and Revert-button

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#102]
When adding/changing a Tag or a Category of a class, prg, form, report, etc. user opens the combobox with a mouse-click, choose a Tag or a Category, than had to close the combobox to do a save or revert (The combobox is over the Save- and the Revert-button).
Therefor, push the Save- and the Revert-button from Center to the left and place the buttons under the labels.
This saves one mouseclick; when adding many Tags or Categorys a user can save time ;-)

![addintagsorcategory](https://user-images.githubusercontent.com/29651009/33243004-d344989c-d2dd-11e7-9bfe-2a88234e2f7b.jpg)

**Comment by DougHennig** [comment]
The ComboTree control doesn't tell the form about the items you've checked until you close it. While this could be changed, I don't see a big benefit from this because, as you noted, it only saves a single mouse click.
