### ISSUE TITLE
Better way to filter on Tags

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#103]
A better way is needed to filter on Tags than Item.Tags.GetKey(1) = 'Classes'
Add a cTags-property to collection for all Tags with content like the Tags-combobox.
Sample: cTags = 'Classes,Pic,Key'
Filter: 'Pic' $ Item.cTags

**Comment by lscheffler** [comment]
Have you tried the Filter form (That with the funnel symbol) ? It allows to enter valid VFP expressions.

**Comment by HaPe4** [comment]
Of course :-)
It works bumby with Category:
`Item.Category = 1`
for all classes, prgs, etc. marked red
User has to use an integer-comparison although Category seems with 'None', 'Red', etc. to be a character.

It doesn'nt work for Tags: 
`Item.Tags`
is a collection and 
`Item.Tags.GetKey(1)`
gives you the first Tag from 'Classes,Pic,Key' => 'Classes'.
How will user can check if 'Pic' is a valid Tag?

**Comment by lscheffler** [comment]
`!EMPTY(Item.Tags.GetKey('Pic'))`

means the Key _Pic_ is existing

**Comment by HaPe4** [comment]
Thanks Lutz, this works.

PS: I think i have to learn more about collections :-(

**Comment by lscheffler** [comment]
It's akward, so I let it open to Doug.

It was just to help you out.

**Comment by DougHennig** [comment]
The combobox in the Project Explorer toolbar is essentially a filter on tag. Do you mean that you want to filter on more than one tag at a time?

**Comment by HaPe4** [comment]
Yes, this situation will exist.

**Comment by DougHennig** [comment]
In the latest release, Tags is now a comma-delimited string instead of a collection, so you can use a filter like 'sometext' $ lower(Item.Tags).
