### ISSUE TITLE
Save Sort and Filter conditions by name

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#104]
Add a save and reload-function by name for Sort and Filter conditions for actual project / all projects.

**Comment by mikepotjer** [comment]
I think this would be quite useful, particularly for filters. I could store frequently used filters in my clipboard manager, but that isn't quite as convenient.

**Comment by DougHennig** [comment]
Done in the latest build. It saves the settings to an XML file with a .filter extension, which can specify the name and path for, so you could put them in a Filters subdirectory, for example.

**Comment by mikepotjer** [comment]
I gave this a try, and it worked well.
