### ISSUE TITLE
Add an option to fix references to a class when its name changes

### ISSUE THREAD

**Issue by TamarEGranor** [DougHennig/ProjectExplorer#108]
Changing the name of a class is an easy way to break things. It would be great to have an option for references to get fixed automatically. There should be code in Class Browser that can be leveraged for this.

**Comment by lscheffler** [comment]
Option or a dialoge after renaming the class to start the process. This will not polute the mask.
I can provide the code to parse / alter all vcx / scx. 

Edit:

prg is a bit more tricky to parse ...

**Comment by DougHennig** [comment]
I'm marking this as Won't Fix because it's complicated and could be handled with a plugin.
