### ISSUE TITLE
WLC ProjectBuilder Toolbar is not displayed

### ISSUE THREAD

**Issue by rschummer** [DougHennig/ProjectExplorer#109]
Doug, in Frankfurt I mentioned how the WLC ProjectBuilder toolbar was not displaying when I opened ProjectExplorer, but it opens fine when I open project in Project Manager. The reason is when you use the NOSHOW on the MODI PROJ, it does not fire the Activate method on the Projecthook. This is where I have the code to call a couple of processes including changing the current folder to the project folder and make sure the ProjectBuilder toolbar is instantiated.

More of a bug in VFP, not ProjectExplorer. Just closing the loop.

**Comment by rschummer** [comment]
One workaround for this is to use Rick Borup's addin for the ProjectBuilder. However, it needs one line of code added to the Init Method of the button class to show the toolbar. Here is all the code in my version of the Init:

```
	function Init
		This.oWLCProjectBuilderToolbar = newobject('tbrProjectTools', ;
			This.cWLCProjectBuilderClass)
                * RAS 29-Nov-2017, added the show to display the toolbar.
                this.oWLCProjectBuilderToolbar.Show()
		return vartype( This.oWLCProjectBuilderToolbar) = 'O' and ;
			not isnull( This.oWLCProjectBuilderToolbar)
	endfunc

```
Sorry for the funky code in this edited message.

**Comment by DougHennig** [comment]
I made Project Explorer call the project hook's Activate method when it opens a project because someone else's project hook may have behavior there.

**Comment by rschummer** [comment]
Excellent idea.

 

Rick

White Light Computing, Inc.

 

www.whitelightcomputing.com

586.254.2530 - office
