### ISSUE TITLE
OPEN Tables in DEFAULT DATASESSION or SET DATASESSION to ProjectExplorer-DATASESSION

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#110]
When clicking or double-clicking a Table in ProjectExplorer the browse-window or the table-designer opens the table in the ProjectExplorer-DATASESSION.
When I try to do some commands in command-window i have to set the correct DATASESSION before.
Either set the DATASESSION in VFP-IDE to the ProjectExplorer-DATASESSION or open the Table in the DEFAULT DATASESSION.

**Comment by DougHennig** [comment]
Done in the latest release.

**Comment by HaPe4** [comment]
This works for the BROWSE- but not for the MODIFY-option from context-menue of the treeview :-(
When I do a MODIFY and hope to close the table with a USE in command-window, the "MODIFYed" table is not closed. When I start my application in a second instance or the EXE => File is in use exclusively.

**Comment by DougHennig** [comment]
Fixed in the latest release.
