### ISSUE TITLE
Unable to create a new solution file

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#111]
When I run Project Explorer for a project that does not have a solution file, the Save dialog appears with the default folder selected, and the file name populated in the dialog. But when I click the Save button, I just get a messagebox that says "That folder does not contain a solution file." Um, yeah, I want to create one. :) When I click OK in the messagebox, Project Explorer just shuts down, and will not create a new solution file. This happens using the most recent version of Project Explorer available through Thor (1.0.6536), and the most recent version from the GitHub repository.

**Comment by DougHennig** [comment]
You have to select a PJX file if there is no solution file.

**Comment by mikepotjer** [comment]
Ah, OK, that works. I had a project open with the VFP Project Manager, so I guess between that and the "Save" button I just assumed it would figure out to create a new solution for the project I had open. I didn't occur to me to change the file type, even though I remember now that PJX was another choice. Maybe the messagebox could include a little more info, like "Hey dummy, try changing the file type to Project." :)

**Comment by DougHennig** [comment]
I guess I could make PJX the default choice if there's no Solution.xml in the current folder.
