### ISSUE TITLE
TEMP-file in SYSTEM-root

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#112]
When ProjectExplorer ist started, a temp-file is created in system-root.

![temp_file_in_root](https://user-images.githubusercontent.com/29651009/33625493-16f9c37a-d9f8-11e7-9f5e-2fa34a26400d.jpg)

Content: 
Gespeicherte Prozeduren in Datenbank CONFIGINDIGO:
  createid
This means:
Stored Procedures in Database CONFIGINDIGO:

**Comment by DougHennig** [comment]
I doubt Project Explorer is doing that. Nowhere in the code is a file created with a name of "TEMP".

**Comment by HaPe4** [comment]
I have no doubt.
Please do:
Open ProjectExplorer of a project with a DBC
Filter on Data in ComboBox
Click Databases in TreeView
Open Windows-Explorer-Window in System-Root and watch.
Then Click on the DBC of your project => Ahh, a temp-file is created in sytem-root
The name of the StoredProcedure in my DBC (here createid) is in last record of ProjectExplorer "ProjectName"_MetaData.dbf.
I think you do a "LIST PROCEDURES" :-)
Please check the actual path when you do a LIST PROCEDURES.

**Comment by HaPe4** [comment]
I found the problem in Class ProjectEngine:
I have set my temp-path to C:\TEMP so i get with:
lcFile = sys(2023) + sys(2015) + '.txt'
C:\TEMP_52Q170PRQ.TXT

Change to
lcFile = ADDBS(sys(2023)) + sys(2015) + '.txt'
and i get
C:\TEMP\\_52Q170PRQ.TXT

Hope this helps :-)

I see ProjectExplorer creates a subdir ProjectExplorer in the temp-path.
Maybe you change to line to
lcFile = ADDBS(sys(2023)) + 'ProjectExplorer\\' + sys(2015) + '.txt'

**Comment by DougHennig** [comment]
Fixed in the latest release. Thanks for tracking this down!
