### ISSUE TITLE
can not alter basic sourcecontrol settings

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#114]
I can not alter the basic source control settings via interface? Disabled ...

**Comment by DougHennig** [comment]
Once the version control options are set, the controls are disabled. The reason for that is turning on version control adds the desired files (for example, text equivalents if you chose Text Equivalents Only or Both) to the repository and changing that setting would mean removing the files and possibly adding a different set of files. I thought it might be too much work to support that so I disabled the controls instead. However, I think this is something that needs to be supported so I will make that change at some point.

**Comment by lscheffler** [comment]
Hi Doug,

I'm with you on this.

If the stuff is changed, the user is responsible to work up the files. Just notify and you are done.
So the user can alter mistakes etc. without working up the solution.xml file.
This is one of the reasons why I'm uneasy about the instant generation of the files.
It feels a lot like MS-VSS but at least git is so different that I think one can not simply  create an integration.
To understand if a class need to be generated to text or if the text file is the result of some _git reset_ or _git checkout_ or _git merge_ and need to be rebuild as a class, that's tricky.

**Comment by lscheffler** [comment]
Hi Doug,

I'm with you on this.

If the stuff is changed, the user is responsible to work up the files. Just notify and you are done.
So the user can alter mistakes etc. without working up the solution.xml file.
This is one of the reasons why I'm uneasy about the instant generation of the files.
It feels a lot like MS-VSS but at least git is so different that I think one can not simply  create an integration.
To understand if a class need to be generated to text or if the text file is the result of some _git reset_ or _git checkout_ or _git merge_ and need to be rebuild as a class, that's tricky.

**Comment by DougHennig** [comment]
The latest release allows you to change the Binary Files in Repository setting in the Version Control Properties dialog.
