### ISSUE TITLE
request

### ISSUE THREAD

**Issue by gabirom** [DougHennig/ProjectExplorer#115]
it possible to group forms/code/class to a sublevels ?
i have a big project an i need to group forms by modules
like 
forms
     - accounting
            form_a
            form_b
    - payroll
        form_p1
       form_p2

Gabi Ionescu
Romania

**Comment by DougHennig** [comment]
Hi Gabi.

You can create your own tags using the Tag Editor in the menu, then assign those tag to various items. For example, you can assign the Payroll tag to form_p1 and form_p2. When you choose Payroll from the tag combobox at the top, only items with that tag appear in the TreeView.

Doug

**Comment by gabirom** [comment]
Thanks ,

 

Cu respect,
