### ISSUE TITLE
Reverse Serialization

### ISSUE THREAD

**Issue by eselje** [DougHennig/ProjectExplorer#122]
I was thinking we do serialization backwards in VFP. It'd be preferable if the binaries *never* saw the light of day except as temporary files while they're being visually edited. Can we tweak Project Explorer to FoxPrg2Bin when a form/report/class is edited, call the editor, and then FoxBin2Prg when finished and then remove the binaries?

**Comment by DougHennig** [comment]
I haven't tried this but I think you could do it in BeforeModifyItem and AfterModifyItem addins.

**Comment by eselje** [comment]
Great tip, thanks. I'll play with it!
