### ISSUE TITLE
Error 1426 when opening Project Explorer

### ISSUE THREAD

**Issue by IanSimcock** [DougHennig/ProjectExplorer#124]
I get a 1426 error in LoadImages when it tries to add the additional images to the ListImages control.
The error in on line 27 of ProjectExplorerFormDockable.oTreeViewContainer.LoadImages with is -
.ListImages.Add(lnImage +  1, 'classlib', loadpicture(lcPath + 'projectexplorerclasslib.ico'))
It's already added 20 images, but fails at this point.

As an additional point of interest, having gotten this error I then get errors if I do anything that activates the form since the form's Activate tries to go through the oAddIns collection, which doesn't yet exist. Nothing major but I thought I'd mention it.

**Comment by DougHennig** [comment]
When that error occurs, is there a file named projectexplorerclasslib.ico in the path specified in the lcPath variable?

**Comment by IanSimcock** [comment]
Yes, along with a whole lot of other icons. The path is pointing to the
correct location (My Thor directory followed by \thor\tools\apps\project
explorer\source\Images\).
My apologies, but I just realised that while I included the error number, I
didn't include the error message. Given that OLE Errors don't mean as mu ch
without that here it is -
OLE IDispatch exception code 0 from ListImages: Index out of bounds.

I've brought the debugger up and stepped thought the first part of
LoadImages and can see that it has no problems adding the 20 icons for the
appropriate classes from the laClasses array, but then it errors at the
point it's adding the manually listed icons.

**Comment by DougHennig** [comment]
Is this line of code just before the one causing the error:

lnImage = .ListImages.Count

If not, it should be. If it is there, what is the value of lnImage after that line executes?

**Comment by IanSimcock** [comment]
Nope, it's the line I mentioned.
lnImage is 20 when the error occurs and I can look at .ListImages.Count in
the debugger after the error has triggered and see it's still 20.

Further investigation shows that the earlier code was also failing but the
Try/Catch was hiding it.

I just wrote a program to list all of the ico files in that directory and
try and LoadPicture them. It turns out that 26 of the icons load fine, but
the other 43 fail with an Unknown Com Status Code error.

Explorer and Paint have no problem with them, and I made the code step
through the icons and set _Screen.Picture to each one and VFP had no
problem, so I don't know what's wrong with LoadPicture, but that's the
problem.

Thanks for looking into this by the way.

**Comment by DougHennig** [comment]
I used this code to test the images:

```
lnFiles = adir(laFiles, 'source\images\*.*')
for lni = 1 to lnfiles
	try
		loadpicture('source\images\' + laFiles[lni, 1])
	catch
		? laFiles[lni, 1]
	endtry
next
```

Not a single one fails. So, either the images on your machine are corrupted or there's some other problem with your system.

**Comment by raulGuiyermo** [comment]
I have the same problem.
It's seem that problem is related with the number of colors of the icon. For example, the ProjectExplorer.ico has true color - 32 bits.

You can reproduce this error by using:

`lo = LoadPicture("ProjectExplorer.ico")`

If you change the icon file to 256 colors - 8 bits the problem will be resolved.

More information:
[https://myvfpblog.blogspot.com.es/2011/04/loadpicture-functionsome-myths-revealed.html](url)

**Comment by DougHennig** [comment]
Thanks for the suggestion and the link. I converted all images that had more than 256 colors to 256 colors in the latest build. Let me know if you still have a problem.

**Comment by DougHennig** [comment]
Just checking to see if that resolved the issue,

**Comment by raulGuiyermo** [comment]
Perfect!
Thank you very much.

**Comment by IanSimcock** [comment]
Thanks Doug, that worked for me too.

Ian.
