### ISSUE TITLE
Error when opening Project Explorer

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#125]
![image](https://user-images.githubusercontent.com/33526380/36661345-0fa50afa-1aec-11e8-974a-6311e4b83fb0.png)

**Comment by DougHennig** [comment]
Delete the _MetaData.dbf file for your project (for example, if you project is named MyProject.pjx, delete MyProject_MetaData.dbf) and the error will go away.
