### ISSUE TITLE
Error displaying "All"

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#126]
When I try to select "All" from the tag dropdown list, I'm getting an error in the LoadSolution() method of the project explorer form:
![image](https://user-images.githubusercontent.com/9847353/40007859-e5956d9c-576b-11e8-8743-416d15d138a6.png)

The value of This.cFilterTags = "", so laTags[] is not being populated, laTags[1] = .F., and that is copied to lcTag.

**Comment by DougHennig** [comment]
This issue is fixed in the latest build too.
