### ISSUE TITLE
Unable to use tags containing a space

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#127]
I created a tag with a space in the name, and get this error when I try select it from the dropdown list:
![image](https://user-images.githubusercontent.com/9847353/40008396-3206d016-576d-11e8-9f66-59adb23428f3.png)

This is in the project explorer form's LoadSolution() method, here:
![image](https://user-images.githubusercontent.com/9847353/40008631-c54f6446-576d-11e8-9451-ec8309acdc94.png)

The value of lcName is "oTVVMP Framework" (note the space is carried over from the tag name to the name being used to create the object). ProjectExplorer does end up loading the correct items in the tree view, but it has a couple side effects:

- The next tag selected from the dropdown doesn't change the tree view (for example, switching to "Classes"). It appears that the view for the tag with the space in it is stored in "Classes" in this example until the ProjectExplorer form is closed.
- When the ProjectExplorer form is closed, the cleanup process tries to save tree view settings, and it fails again on the tag with the spaces in it.

The Tag Editor allows the user to enter all kinds of special characters, so I expect there are other characters that could be used in a tag name that would cause the same errors.

**Comment by DougHennig** [comment]
Thanks for finding this, Mike. Fixed in the latest build.

**Comment by mikepotjer** [comment]
Thanks Doug. I tried the new build, and it is working properly now for both of the tag-related situations I reported.
