### ISSUE TITLE
Problem tagging classes in "new" project

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#128]
I was trying to assign a tag to a number of files with the Assign Tags to Items tool using an expression like this:
`"\FOLDER\" $ UPPER( Item.Path )`
When I selected the tag from the dropdown, the class libraries all showed up, but the classes within the class library were not tagged. Long story short, it appears that if the tree view node for a class library has **never** been expanded, the Assign Tags tool will not find the classes in that class library.

**Comment by DougHennig** [comment]
Fixed in the latest build.

**Comment by mikepotjer** [comment]
Thanks Doug. I tried this out this morning, and it's working well for me.
