### ISSUE TITLE
Repository Browser causes VFP to hang

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#129]
When I try to run the Repository Browser, it just hangs VFP. I don't know what that tool does (which is why I tried to run it), and there is no messaging to indicate what it is trying to do. My last couple of attempts, I let it go for more than 5 minutes with no response. If I try to do anything in VFP after selecting this item, I just get the "not responding" message shown here.
![image](https://user-images.githubusercontent.com/9847353/40121888-9702af24-58f0-11e8-9a66-368f2a219e94.png)
This isn't critical to me, but just wanted to make sure you were aware of it.

[Update] I looked at the code to see what it was doing, and saw there were 2 possible commands it tries to execute. Since I have TortoiseGit installed, I assume it was trying to run the command `TortoiseGitProc /command:repobrowser`. When I run that command from the Windows command prompt, it works fine. I also tried the `gitk` command, and that worked, too. Odd that it isn't working from VFP.

**Comment by DougHennig** [comment]
I just tried it and it worked for me. What happens if you set llVisible to .T. for the TortoiseGitProc command?

**Comment by mikepotjer** [comment]
Sorry, now that you've asked it's working. 😕 The lUseTortoise flag was already true, so it is using TortoiseGitProc. When I wrote the first message, it was failing every time, and that included killing and reopening VFP several times. Now I can't reproduce it all. If I'm able to figure out some way to reproduce this, I'll post more info. Otherwise it seems like some kind of fluke.

**Comment by mikepotjer** [comment]
This feature is still working fine for me now, so I don't know what the problem was. I don't think I had ever opened the TortoiseGit repo browser before this, but it seems unlikely that would have been the problem.
