### ISSUE TITLE
Addins: MyTools vs. Addins folder

### ISSUE THREAD

**Issue by rschummer** [DougHennig/ProjectExplorer#130]
Each time a new release happens the Addins folder overwrites the Addins folder. Based on the architecture and the addin, I have to edit the source code of the PRG to turn it on or off. Next update resets my choices. I am using Beyond Compare to check the changes, but that is only if I am not using Thor's Check For Updates, which overwrites the current folder.  

Suggestion: how about the Addins folder be the base folder for the source code, and we create a MyAddins (similar to the MyTools in Thor). This way the base Project Explorer extensions can be updated and new ones released. Also, you could use both if you wanted, just make the MyAddins folder take precedent via pathing. Not trivial, but certainly doable.

**Comment by mikepotjer** [comment]
Project Explorer ships with a cool add-in to add the amazing HackCX tool to the shortcut menu, but it isn't active by default. I copied that add-in to the MyAddins folder and set it to active. The MyAddins enhancement worked as advertised.

(Mike is not an actor. No goods were received in exchange for this testimonial.)

**Comment by rschummer** [comment]
Mike, are you saying Doug already added this?

**Comment by mikepotjer** [comment]
Yep, this afternoon. Within a couple hours of when you asked for it.

**Comment by DougHennig** [comment]
Yes, for some reason my comment here that the issue was done didn't get posted.
