### ISSUE TITLE
SET STEP ON in latest build

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#131]
In the 1.0.6710 build created today, there is a SET STEP ON in the NewItem() code to create a form.
![image](https://user-images.githubusercontent.com/9847353/40143844-8d18d544-592a-11e8-92cb-4297d449bfcf.png)

Yes, I happened to have checked for a new build in Thor CFU, and it happened to contain the new New Form dialog, and I happened to need to create a new form. Lucky you! 😄

**Comment by DougHennig** [comment]
Doh! Fixed. Thor CFU won't see it because the version number is the same (tied to the date) but you can download it from here.

**Comment by mikepotjer** [comment]
Although Thor CFU shows that Project Explorer is current, you can still select it and reinstall it, in which case the latest version is downloaded and installed. That's what I did. This issue is resolved for me.
