### ISSUE TITLE
Classes disappear with latest build

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#133]
Hi Doug,

There may be an issue with the latest commit. I downloaded a copy of just the .APP file into Thor folder for Project Explorer to test #132. When I went to the class library I was reviewing, 2 of the classes were not visible. I switched the tag to 'Classes' and 'All', just to make sure it wasn't a tag issue, and that didn't make a difference. This is what it looks like with the latest commit:
![image](https://user-images.githubusercontent.com/9847353/40254850-0a97f958-5ab3-11e8-98f2-8f803b908fe1.png)
I then reinstalled the release version via Thor, and the same class library looks like this, with the 2 missing classes highlighted:
![image](https://user-images.githubusercontent.com/9847353/40254889-2fb379f6-5ab3-11e8-9039-8e6074f67a0c.png)

To make sure, I put the new .APP back in and classes disappeared again. I put the release version back, and they reappeared. The only clue I have is that I was viewing those 2 classes in the designer about the time I was checking out the new Project Explorer change. I didn't make any changes to them, just viewed them in the designer.

Mike

**Comment by DougHennig** [comment]
Try the latest build and let me know if it resolves the problem.

**Comment by mikepotjer** [comment]
It might have to wait until Monday, if that's OK. It was on the office PC, and I'm home now, so I'm not sure I'll be able to recreate the same conditions.

**Comment by mikepotjer** [comment]
Based on the changes you made, I should be able to reproduce it here. I'll get back to you on this.

**Comment by mikepotjer** [comment]
OK, that fixed it. I was able to reproduce the issue with the previous build, then copied the latest build to my tool folder and the classes are visible again.
