### ISSUE TITLE
Behavior Commit All x Commit File

### ISSUE THREAD

**Issue by DionisioSilvaJunior** [DougHennig/ProjectExplorer#134]
Hi Doug,

I'm using GIT, VFP9 and Project Explorer 1.06710

Configured for:
- "Solution uses version control"
- "Version control provider: Git"
- "Text equivalents, no binary files"

Everything is working very well, but

When right clicking -> "Commit All", the files that are changed are not being Commitaded.

When right clicking -> "Commit Files" works perfectly.

In other words, "Commit File" staged the file and commit it, "Commit All" only works if before I staged the changed files.

Is this behavior correct?

BTW: Great job. Congratulations !

**Comment by DougHennig** [comment]
Fixed in the latest build.

Thanks!
