### ISSUE TITLE
Display "parent" when a "child" matches a filter

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#135]
The specific use case is that I am trying to set a filter to view all classes that meet a condition like this: `lower( Item.ItemBaseClass ) = 'textbox'`. I have the tag set to 'Classes'. As soon as I apply the filter, the entire list is cleared, and all I see is the project itself.
![image](https://user-images.githubusercontent.com/9847353/40372397-948d352c-5db2-11e8-97ac-113f76e18564.png)
ISTM that the necessary parent nodes should be included automatically when a child node matches the filter.

**Comment by DougHennig** [comment]
I can't reproduce that: here's what I get when I use lower(Item.ItemBaseClass) = 'checkbox':

![pe](https://user-images.githubusercontent.com/12052409/40375155-61324d18-5db0-11e8-9f3f-f889366148f5.png)

I can reproduce it if I use a filter for which nothing matches, such as lower(Item.ItemBaseClass) = 'xxx'.

**Comment by mikepotjer** [comment]
This appears to be another lazy loading issue. I tried again, and it showed the 3 class libraries that I expanded after creating this issue. Then I cleared the filter, expanded another class library with a textbox in it, and when I reapplied the filter, I now had 4 class libraries showing.
So you should be able to recreate this with a "clean" project that hasn't been opened in Project Explorer before.

**Comment by DougHennig** [comment]
Thanks for tracking that down. Try the latest build.

**Comment by mikepotjer** [comment]
I first tried filtering again with the 1.0.6710 version when I first opened Project Explorer, and got no results.
I then replaced the .APP with the new 1.0.6716 version, and applied the same filter. This gave me the list of results I expected.
This appears to be fixed now. Thanks Doug!
