### ISSUE TITLE
FontSizer-Addin SetFont

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#137]
Hello Doug,

beginning from last but one version of ProjectExplorer, the FontSizer-Addin SetFont is not called in all cases.
When "All" options for treeview is selected, the font-size is set to the value in SetFont.
If i select "Other", it seems the FontSizer-Addin SetFont ist not triggered.
![fontsize](https://user-images.githubusercontent.com/29651009/40646913-da904ea6-632a-11e8-9074-f9823fdc7d1b.jpg)
-- 
Hans-Peter

**Comment by DougHennig** [comment]
Fixed in the latest release.
