### ISSUE TITLE
Copy tag or category to child items

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#139]
When setting a tag or category on a parent item, it would be nice if there were at an option to copy that setting to all children of the parent. I'm thinking of class libraries in particular, though it could certainly apply to items like a database. The project level might be the only exception.
Maybe this could just be a checkbox on the settings page for the item, so that it's something that is always a decision that we make as we are about to save the settings for that item.

**Comment by DougHennig** [comment]
If you change Tags or Category for a parent item, you're now prompted if you want child items to have the same values in the latest build.

**Comment by mikepotjer** [comment]
I tested this a little, and it appears to work as advertised. Thanks!
