### ISSUE TITLE
Assign or clear category for multiple items

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#140]
Because assigning a category is intended to be something temporary, it would be nice to have a way to easily assign a category to multiple items at once (#139 would help with this, too). As a complement to that, it would be helpful to be able to clear a category from multiple items, or all items.

**Comment by DougHennig** [comment]
In the latest build, the Assign Tags function is changes to Add or Remove Tags/Category, which handles adding or removing tags and category from parent and optionally child items.

**Comment by mikepotjer** [comment]
I had occasion to try this out for assigning tags, and it appears to work. I haven't tried clearing anything yet.

**Comment by mikepotjer** [comment]
I needed to clear a tag from some class libraries and their classes yesterday, and that worked well for me, too. Thanks!
