### ISSUE TITLE
Spaces in tag names

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#141]
Being inspired by this weekend's presentation, I added a custom tag to a solution and ran into problems, apparently because I used a space in the tag name. PEX didn't seem to like that. I manually cleaned up the metadata tables properly ( I think) but now when I try to open this solution, it is throwing errors in the loadsolution method. this.cFilterTags is empty and therefore laTags contains a single boolean element. Which then goes boom on this line:

lcName = 'oTV' + lcTag

I'm using v1.0.6691

**Comment by DougHennig** [comment]
Hi Richard.

That was fixed in a newer version a few weeks ago.

Doug

**Comment by rikaye** [comment]
Thanks, Doug. I just got build 1.0.6733 from Thor.
