### ISSUE TITLE
Enhancement request:  Add option to change search behavior for solution.xml

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#142]
PEX appears to walk the VFP search path to find solution.xml. Because of the way I have my environment configured, PEX is always opening up the solution.xml file in my default development directory, which is also in my VFP search path. For example, if my dev environment looks like this:

main folder 
-> folder 1
-> folder 2

If I change to "folder 1" and I want to create a new solution there, PEX still opens the solution found in "main folder", because it is in my VFP search path. I have also tried using the Open button and it does not appear to do anything once a solution is loaded.

**Comment by DougHennig** [comment]
Fixed a number of issues related to this in the latest build. I haven't updated the Thor package yet, so you can just download the files from here.

**Comment by rikaye** [comment]
Thanks, Doug. I'll clone it from here. (Getting my head wrapped around the git intregration is one of the primary reasons I want to start using PEX.)
