### ISSUE TITLE
Enable MultiSelect when adding files

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#145]
Hello Doug !

Please enable multiselect in file-selection when adding files (by green plus-sign) to the project like VFP-project-manager.
Normaly no problem adding only one file at once; but adding bitmaps or icons one by one is very time-consuming.

-- 
Hans-Peter Grözinger

**Comment by DougHennig** [comment]
This is done in the latest build. Thanks for the suggestion.
