### ISSUE TITLE
Source Control and common files folder

### ISSUE THREAD

**Issue by johnniekipper** [DougHennig/ProjectExplorer#146]
I have added my projects/folders to Mercurial, like this 

Project 1 
Project 2
Common Files folder

When I view Project1 in the project explorer, I can see the common elements in there too. If I change one it shows an exclamation mark icon to show it has changed. However , when I exit VFP and go in again and open the project it has switched back to a green (no changes) icon. In tortoise , I can see the changes I made but is there no way I can see them in project explorer ?

**Comment by DougHennig** [comment]
Edit solution.xml and in the versioncontrol element, change the value of the repository attribute to be the folder containing the .hg folder. In other words, it should be the parent of the Project 1 folder.
