### ISSUE TITLE
Error clicking on the button F2

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#152]
Version 1.0.6754
![f2_err](https://user-images.githubusercontent.com/33526380/43999192-3c3d2a1e-9e10-11e8-80c1-b29bdc603237.PNG)

**Comment by DougHennig** [comment]
I cannot reproduce that: when I press F2 when the Name textbox has focus, nothing happens. Please give me steps to reproduce the issue.

**Comment by AnatolBazyukin** [comment]
Version 9.00.0000.7425
Clear VFP
DO "D:\VFPTools\Thor\Thor\Tools\Apps\Project Explorer\projectexplorer.app" WITH "d:\ct\ct.app"
First pushing of F3 - F9 without leaving VFP window leads to the above shown message! Transfer to another window and back stops the message showing.
![debug](https://user-images.githubusercontent.com/33526380/44048947-724d8816-9f3b-11e8-92b2-9394bd7020e3.JPG)

**Comment by DougHennig** [comment]
OK, thanks. Fixed in the latest release.
