### ISSUE TITLE
Run Main Program on toolbar

### ISSUE THREAD

**Issue by johnniekipper** [DougHennig/ProjectExplorer#155]
Could a button be added to the toolbar for the frequently used **Run Main Program**.

**Comment by DougHennig** [comment]
You can do that by creating an add-in. See AddWLCProjectBuilderButton.prg in the Addins folder for an example of adding a button to the toolbar. Look at RunMainProgram.prg to see how it runs the main program. You can then create a new program that combines the two techniques.
