### ISSUE TITLE
Impossibility to add to Classes

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#157]
If there are no classes in the project, they cannot be added.

**Comment by DougHennig** [comment]
Yes, you can add a class to a project. Choose the Classes tag and click either the Add button to add an existing VCX file or click the New button to create a new VCX. Then select the VCX and click New to create a new class in that VCX.

**Comment by AnatolBazyukin** [comment]
I poorly explained the problem. 
We have a project without VCX, created by foxpro project manager.
When the opening of this project in the project explorer on  the Classes tag the Add button is not available.

**Comment by DougHennig** [comment]
Thanks for the explanation. Choose Options from the menu and turn on Add and New Allow Any File Type.
