### ISSUE TITLE
Assign VCX tags to new class & refresh node for that VCX

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#159]
Here is the use case:
- A custom tag is selected.
- I add a class to a class library included in that tag.
- When the new class is saved, ProjEx switches to the predefined Classes tag.
- I have to view the properties for the new class, and assign the class to the same custom tag as the class library.
- I switch the filter back to the custom tag, and have to refresh the view because the cached nodes do not include the new class I just added. This refresh can take a couple seconds when there are a lot of nodes to refresh.

It would be nice if this whole process could be streamlined:
- If the class library has one or more custom tags assigned to it, automatically assign those tags to the new class when it's saved. It's fine if I have to respond to a prompt asking if that's what I want to do.
- If the tree view is filtered on a custom tag, and that tag was just auto-added to the new class, leave the tree view filtered on that tag (rather than switching to the predefined Classes tag).
- Automatically refresh the node for the class library to which the new class was just added (not the entire tree view), so the new class is visible with the filter set to the custom tag.

**Comment by DougHennig** [comment]
Implemented in the latest build.

**Comment by mikepotjer** [comment]
Thanks Doug! Just tried it out, and it worked exactly as expected. I'm glad to see it didn't much code to implement either. This is going to save a lot of time!
