### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#162]
When I try to open a file with a non-English name for editing on the Code tab, an error appears.
![error](https://user-images.githubusercontent.com/33526380/53187173-9b579e80-3613-11e9-9010-6e50bd42d13c.JPG)

**Comment by DougHennig** [comment]
Please zip your PJX and PJT files plus the file you want to edit and attach the zip file here so I can reproduce and fix the problem.

**Comment by AnatolBazyukin** [comment]
Example
[test.zip](https://github.com/DougHennig/ProjectExplorer/files/2895814/test.zip)

**Comment by DougHennig** [comment]
Fixed in the latest build.
