### ISSUE TITLE
Error: String is too long to fit.

### ISSUE THREAD

**Issue by mattslay** [DougHennig/ProjectExplorer#164]
Using the latest version just release, I am getting this error in various place throughout the app:

![2019-02-23 07_19_08-microsoft visual foxpro](https://user-images.githubusercontent.com/309016/53286977-6ba3b600-373b-11e9-9354-807ebc3c6ced.png)

Since this error appears related to Path, here is the current path in my IDE at the time, in case this a factor, note that my current path is dynamically set by scanning certain folders and their subfolders of my source directories and referenced libraries used in my app.

(This is only active during development mode; at runtime The path setting if much more concise.)

?Set("PATH") returns:

H:\WORK\LM5\APPDATA;H:\WORK\LM5;H:\WORK\LM5\REPORTS;H:\WORK\LM5\BARCODE READER\;H:\WORK\LM5\BIN\;H:\WORK\LM5\BIN\DEBUG\;H:\WORK\LM5\BIN\RELEASE\;H:\WORK\LM5\CLASSES\;H:\WORK\LM5\CLASSES\WWLM\;H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\;H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\LM\;H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\LM\LIB\;H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\LM\LIB\WW_622\;H:\WORK\LM5\CLOCK2\;H:\WORK\LM5\CLOCK2\ICONS\;H:\WORK\LM5\CLOCK2\ICONS\NEW FOLDER\;H:\WORK\LM5\CLOCK2\IMAGES\;H:\WORK\LM5\CLOCK2\IMAGES\CHRISTMAS\;H:\WORK\LM5\CURSORS\;H:\WORK\LM5\FORMS\;H:\WORK\LM5\HTML\;H:\WORK\LM5\ICONS\;H:\WORK\LM5\IMAGES\;H:\WORK\LM5\LMDB_SCRIPTS\;H:\WORK\LM5\LMDB_SCRIPTS\LMDB\;H:\WORK\LM5\LMDB_SCRIPTS\LMDB\SCHEMAS\;H:\WORK\LM5\LMDB_SCRIPTS\LMDB\STOREDPROCEDURES\;H:\WORK\LM5\LMDB_SCRIPTS\LMDB\TABLES\;H:\WORK\LM5\LMDB_SCRIPTS\LMDB\USERDEFINEDFUNCTIONS\;H:\WORK\LM5\LMDB_SCRIPTS\LMDB\VIEWS\;H:\WORK\LM5\MENUS\;H:\WORK\LM5\NOT USED\;H:\WORK\LM5\OBJ\;H:\WORK\LM5\OBJ\DEBUG\;H:\WORK\LM5\OBJ\DEBUG\TEMPPE\;H:\WORK\LM5\PRG\;H:\WORK\LM5\PROPERTIES\;H:\WORK\LM5\QB\;H:\WORK\LM5\REPORTS\DYMO\;H:\WORK\LM5\TESTS\;H:\WORK\LM5\VENDOR\;H:\WORK\LM5\VENDOR\APPTABS\;H:\WORK\LM5\VENDOR\CALENDAR\;H:\WORK\LM5\VENDOR\CALENDAR\HELP\;H:\WORK\LM5\VENDOR\CALENDAR\IMAGES\;H:\WORK\LM5\VENDOR\CTL32\;H:\WORK\LM5\VENDOR\CTL32\COLORPICKER\;H:\WORK\LM5\VENDOR\FELTMAN\;H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\;H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\FORMS\;H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\IMAGES\;H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\REPORTS\;H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\SAMPLES\;H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\SOURCE\;H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\;H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\SAMPLES\;H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\SAMPLES\IMAGES\;H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\SOURCE\;H:\WORK\LM5\VENDOR\GHOSTSCRIPT 32-BIT INSTALL\;H:\WORK\LM5\VENDOR\GRIDEXTRAS\;H:\WORK\LM5\VENDOR\GRID_HIGHLIGTER\;H:\WORK\LM5\VENDOR\INGRID\;H:\WORK\LM5\VENDOR\JIMNELSON\;H:\WORK\LM5\VENDOR\NFJSON\;H:\WORK\LM5\VENDOR\NFJSON\PERFORMANCETEST\;H:\WORK\LM5\VENDOR\NFJSON\TESTS\;H:\WORK\LM5\VENDOR\NFJSON\TESTS\JSONSAMPLES\;H:\WORK\LM5\VENDOR\NFJSON\TESTS\TEMP\;H:\WORK\LM5\VENDOR\SANDSTORM\;H:\WORK\LM5\VENDOR\SEDNA\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\BACKUP\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\BACKUP\VISTADIALOGS4COM\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\BACKUP\VISTADIALOGS4COM\MY PROJECT\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\BIN\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\BIN\DEBUG\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\MY PROJECT\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\OBJ\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\OBJ\DEBUG\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\OBJ\DEBUG\TEMPPE\;H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\VFP SAMPLE\;H:\WORK\LM5\VENDOR\SORTINGGIRD\;H:\WORK\LM5\VENDOR\WORKBOOKXLSX_R29\;H:\WORK\LM5\VENDOR\WW\;H:\WORK\LM5\VENDOR\WW\CLASSES\;H:\WORK\LM5\VENDOR\WW\CLASSES\OLDFILES\;H:\WORK\LM5\VENDOR\WW\CONSOLE\;H:\WORK\LM5\VENDOR\WW\SAMPLES\;H:\WORK\LM5\VENDOR\WW\SAMPLES\WWDOTNETBRIDGE\;H:\WORK\LM5\VENDOR\WW\SAMPLES\WWDOTNETBRIDGE\WWDOTNETBRIDGETEST\;H:\WORK\LM5\VENDOR\WW\TESTS\;H:\WORK\LM5\VENDOR\WW\TOOLS\;H:\WORK\LM5\VENDOR\WW\TOOLS\REFLECTOR\;H:\WORK\LM5\VENDOR\WWBUSINESSPRO\;H:\WORK\LM5\VENDOR\WW_622\;H:\WORK\LM5\VENDOR\WW_622\CLASSES\;H:\WORK\LM5\VENDOR\WW_622\CONSOLE\;H:\WORK\LM5\VENDOR\WW_622\TOOLS\;H:\WORK\LM5\VENDOR\WW_622\WWIPSTUFF_SAMPLES\;H:\WORK\LM5\VENDOR\WW_622\WWIPSTUFF_SAMPLES\WWDOTNETBRIDGE\;H:\WORK\LM5\VENDOR\WW_CUSTOM\;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL FOXPRO 9\SEDNA\MY;C:\PROGRAM FILES (X86)\MICROSOFT VISUAL FOXPRO 9\FFC;H:\WORK\ICONS\GIF\16\;H:\WORK\UTIL\THOR\THOR\TOOLS\APPS\PROJECT EXPLORER;H:\WORK\UTIL\THOR\THOR\TOOLS\APPS\PROJECT EXPLORER\SOURCE

Here is my path in a more human readable format:

```
Current Path: \work\lm5\

H:\WORK\LM5\APPDATA
  H:\WORK\LM5
  H:\WORK\LM5\REPORTS
  H:\WORK\LM5\BARCODE READER\
  H:\WORK\LM5\BIN\
  H:\WORK\LM5\BIN\DEBUG\
  H:\WORK\LM5\BIN\RELEASE\
  H:\WORK\LM5\CLASSES\
  H:\WORK\LM5\CLASSES\WWLM\
  H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\
  H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\LM\
  H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\LM\LIB\
  H:\WORK\LM5\CLIENT SETUP INSTRUCTIONS\LM\LIB\WW_622\
  H:\WORK\LM5\CLOCK2\
  H:\WORK\LM5\CLOCK2\ICONS\
  H:\WORK\LM5\CLOCK2\ICONS\NEW FOLDER\
  H:\WORK\LM5\CLOCK2\IMAGES\
  H:\WORK\LM5\CLOCK2\IMAGES\CHRISTMAS\
  H:\WORK\LM5\CURSORS\
  H:\WORK\LM5\FORMS\
  H:\WORK\LM5\HTML\
  H:\WORK\LM5\ICONS\
  H:\WORK\LM5\IMAGES\
  H:\WORK\LM5\LMDB_SCRIPTS\
  H:\WORK\LM5\LMDB_SCRIPTS\LMDB\
  H:\WORK\LM5\LMDB_SCRIPTS\LMDB\SCHEMAS\
  H:\WORK\LM5\LMDB_SCRIPTS\LMDB\STOREDPROCEDURES\
  H:\WORK\LM5\LMDB_SCRIPTS\LMDB\TABLES\
  H:\WORK\LM5\LMDB_SCRIPTS\LMDB\USERDEFINEDFUNCTIONS\
  H:\WORK\LM5\LMDB_SCRIPTS\LMDB\VIEWS\
  H:\WORK\LM5\MENUS\
  H:\WORK\LM5\NOT USED\
  H:\WORK\LM5\OBJ\
  H:\WORK\LM5\OBJ\DEBUG\
  H:\WORK\LM5\OBJ\DEBUG\TEMPPE\
  H:\WORK\LM5\PRG\
  H:\WORK\LM5\PROPERTIES\
  H:\WORK\LM5\QB\
  H:\WORK\LM5\REPORTS\DYMO\
  H:\WORK\LM5\TESTS\
  H:\WORK\LM5\VENDOR\
  H:\WORK\LM5\VENDOR\APPTABS\
  H:\WORK\LM5\VENDOR\CALENDAR\
  H:\WORK\LM5\VENDOR\CALENDAR\HELP\
  H:\WORK\LM5\VENDOR\CALENDAR\IMAGES\
  H:\WORK\LM5\VENDOR\CTL32\
  H:\WORK\LM5\VENDOR\CTL32\COLORPICKER\
  H:\WORK\LM5\VENDOR\FELTMAN\
  H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\
  H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\FORMS\
  H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\IMAGES\
  H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\REPORTS\
  H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\SAMPLES\
  H:\WORK\LM5\VENDOR\FOXBARCODE_1.12\SOURCE\
  H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\
  H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\SAMPLES\
  H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\SAMPLES\IMAGES\
  H:\WORK\LM5\VENDOR\FOXCHARTS_1.20\SOURCE\
  H:\WORK\LM5\VENDOR\GHOSTSCRIPT 32-BIT INSTALL\
  H:\WORK\LM5\VENDOR\GRIDEXTRAS\
  H:\WORK\LM5\VENDOR\GRID_HIGHLIGTER\
  H:\WORK\LM5\VENDOR\INGRID\
  H:\WORK\LM5\VENDOR\JIMNELSON\
  H:\WORK\LM5\VENDOR\NFJSON\
  H:\WORK\LM5\VENDOR\NFJSON\PERFORMANCETEST\
  H:\WORK\LM5\VENDOR\NFJSON\TESTS\
  H:\WORK\LM5\VENDOR\NFJSON\TESTS\JSONSAMPLES\
  H:\WORK\LM5\VENDOR\NFJSON\TESTS\TEMP\
  H:\WORK\LM5\VENDOR\SANDSTORM\
  H:\WORK\LM5\VENDOR\SEDNA\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\BACKUP\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\BACKUP\VISTADIALOGS4COM\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\BACKUP\VISTADIALOGS4COM\MY PROJECT\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\BIN\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\BIN\DEBUG\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\MY PROJECT\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\OBJ\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\OBJ\DEBUG\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\SOURCE\VISTADIALOGS4COM\OBJ\DEBUG\TEMPPE\
  H:\WORK\LM5\VENDOR\SEDNA\VISTADIALOGS4COM\VFP SAMPLE\
  H:\WORK\LM5\VENDOR\SORTINGGIRD\
  H:\WORK\LM5\VENDOR\WORKBOOKXLSX_R29\
  H:\WORK\LM5\VENDOR\WW\
  H:\WORK\LM5\VENDOR\WW\CLASSES\
  H:\WORK\LM5\VENDOR\WW\CLASSES\OLDFILES\
  H:\WORK\LM5\VENDOR\WW\CONSOLE\
  H:\WORK\LM5\VENDOR\WW\SAMPLES\
  H:\WORK\LM5\VENDOR\WW\SAMPLES\WWDOTNETBRIDGE\
  H:\WORK\LM5\VENDOR\WW\SAMPLES\WWDOTNETBRIDGE\WWDOTNETBRIDGETEST\
  H:\WORK\LM5\VENDOR\WW\TESTS\
  H:\WORK\LM5\VENDOR\WW\TOOLS\
  H:\WORK\LM5\VENDOR\WW\TOOLS\REFLECTOR\
  H:\WORK\LM5\VENDOR\WWBUSINESSPRO\
  H:\WORK\LM5\VENDOR\WW_622\
  H:\WORK\LM5\VENDOR\WW_622\CLASSES\
  H:\WORK\LM5\VENDOR\WW_622\CONSOLE\
  H:\WORK\LM5\VENDOR\WW_622\TOOLS\
  H:\WORK\LM5\VENDOR\WW_622\WWIPSTUFF_SAMPLES\
  H:\WORK\LM5\VENDOR\WW_622\WWIPSTUFF_SAMPLES\WWDOTNETBRIDGE\
  H:\WORK\LM5\VENDOR\WW_CUSTOM\
  C:\PROGRAM FILES (X86)\MICROSOFT VISUAL FOXPRO 9\SEDNA\MY
  C:\PROGRAM FILES (X86)\MICROSOFT VISUAL FOXPRO 9\FFC
  H:\WORK\ICONS\GIF\16\
  H:\WORK\UTIL\THOR\THOR\TOOLS\APPS\PROJECT EXPLORER
  H:\WORK\UTIL\THOR\THOR\TOOLS\APPS\PROJECT EXPLORER\SOURCE

```

**Comment by mattslay** [comment]
Okay, here's an update on this issue.... I went to my development setup script, and I was able to trim down that Path a little bit by removing about 8 entries and the error went away. However, the core issue stills remains if the path folder list is very long.

**Comment by DougHennig** [comment]
Fixed in the latest build.
