### ISSUE TITLE
Adding Free tables

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#165]
Data tab cannot add Free tables

**Comment by DougHennig** [comment]
In the Options dialog, turn on Add and New Allow Any File Type. You can then select a free table when you click the Add button.

**Comment by AnatolBazyukin** [comment]
This error occurs when trying to add a file with a non-English name.
![error](https://user-images.githubusercontent.com/33526380/53360096-b1cc6580-3945-11e9-8b2b-0db3941ed3f6.JPG)
But the next time you open the project, the table is added.

**Comment by DougHennig** [comment]
This is actually coming from VFP. You can reproduce this error from the Command window: open a project and type _vfp.ActiveProject.Files.Add('ÅÑaÑñátá.dbf').

Doug

**Comment by AnatolBazyukin** [comment]
Oddly enough if I run the VFP using "Run As Administrator" it works fine

**Comment by DougHennig** [comment]
In the latest build, I added a TRY around the Add statement so it will just display the message rather than causing an error. You can then right-click the TreeView and choose Refresh to see the added table.
