### ISSUE TITLE
Add another project to solution

### ISSUE THREAD

**Issue by oiBio** [DougHennig/ProjectExplorer#166]
Hello Doug,

i wanted to add an project from a subfolder to the solutions. Unfortunalty this did not work

This is my structure.
D:\dev\ProjectExplorerTest\proj1.pjx
D:\dev\ProjectExplorerTest\proj1.slx

and wanted to add this
D:\dev\ProjectExplorerTest\Launcher\proj2.pjx
but it did not work... 
i could have added this
D:\dev\proj2.pjx or even D:\proj2.pjx

I think you've confused the two parameters in ProjectExplorerForm/AddProjectToSolution()
```
if not empty(lcFile)
	lcPath = upper(justpath(lcFile))
	if lcFolder $ lcPath 
```
it sould be 
```
if not empty(lcFile)
	lcPath = upper(justpath(lcFile))
	if lcPath $ lcFolder 
```

but even with this change there are some other bugs (like not able to open the project from subfolder after restart)

**Comment by DougHennig** [comment]
Currently, Project Explorer only supports projects in the same folder in a given solution. I'll look at this in the future to see if I can support this.

**Comment by DougHennig** [comment]
This is fixed in the latest build.
