### ISSUE TITLE
Fails to build my project with OlePublic class

### ISSUE THREAD

**Issue by Tracy-P** [DougHennig/ProjectExplorer#167]
This is the only file in my test project `mycomobject.prg`:
```
DEFINE CLASS mycomobject as Session OLEPUBLIC 

   PROTECTED PROCEDURE HiddenMethod
      RETURN "From Hidden"
   ENDPROC 
   
   PROCEDURE VisibleMethod
      RETURN THIS.HiddenMethod() + " via the VisibleMethod"
   ENDPROC 
ENDDEFINE
```
Building with the Project Explorer errors with 
```---------------------------
Project Explorer
---------------------------
The build failed. The error message is:

Function argument value, type, or count is invalid.
---------------------------
OK   
---------------------------
```
Building from the project directly **works**.
Building with `_VFP.ActiveProject.Build("testcom.exe",3,.F.,.T..F.)` **works**.

Remove the OLEPUBLIC and compile with Project Explorer, **No error**

Change the code to this:
```
DEFINE CLASS mycomobject as Session OLEPUBLIC 

   PROTECTED PROCEDURE HiddenMethod
   PROCEDURE HiddenMethod
      RETURN "From Hidden"
   ENDPROC 
   
   PROCEDURE VisibleMethod
      RETURN THIS.HiddenMethod() + " via the VisibleMethod"
   ENDPROC 
ENDDEFINE
```

Compile from with Project Explorer, **No error**.

NOTE: I am running VFP with Administrative privileges. The TLB file doesn't get created when things error.

**Comment by DougHennig** [comment]
I can reproduce this but the error is coming from the call to the Build method of the project. I don't know why it gives a different result when called under these conditions from inside an APP than from the command window, but it does and there isn't anything I can do about it.

**Comment by Tracy-P** [comment]
All I could find was to add that extra `PROCEDURE HiddenMethod` line. *(above or below it doesn't matter)*
However, when this is done the **protected** status of the methods appears to be lost because it is visible in VFP's intellisense of the COM object. Try to use it and and hope your error handling in the COM object catches it.

When I compile the project with `_VFP.ActiveProject.Build("testcom.exe",3,.F.)` from the Command window. The protected procedures **are not** visible in VFP's intellisense. 

I'm okay to close this Issue now that this has been documented.

**Comment by rschummer** [comment]
Tracy,

In your second example, the second class method code is the one that should take precedent via the VFP compiler, which is likely the reason you are not seeing the HiddenMethod as protected. Of the two with the same name, only the first one is protected.

**Comment by Tracy-P** [comment]
Rick,
Above or below, I saw the same behavior.

**Comment by Tracy-P** [comment]
Rick, 
Thinking about what you said some more. Yes, the `PROTECTED` declaration should be after.  If the object is used directly within VFP as the desired behavior would then be correct. I was responding to what I was seeing as a COM object.

**Comment by Tracy-P** [comment]
I have come back to this and tinkered with the latest build that fixes the tnBuildAction to be an integer.
This still fails. So I started to tinker. Is it caused by the call depth? No, I went down to eight and it still passed.
When it failed, was when I put the call to the build in a function inside a Custom class.

If the call to `_VFP.Project.Item("mycomproject.pjx").Build(...)` is in a function of a Class, the returned result is `.F.`.
If the class instead calls a Function in a PRG, the returned result is `.T.`.

How odd is that?

```
ACTIVATE SCREEN 
CLEAR 

* call depth
LOCAL llOK
?"Call Depth:",PROGRAM(-1),PROGRAM(PROGRAM(-1))
llOK = TestThis()
?llOK

FUNCTION TestThis
	LOCAL buildAction, llOK
	buildAction = CREATEOBJECT("BuildAction")
	?"Call Depth:",PROGRAM(-1),PROGRAM(PROGRAM(-1))
	llOK = buildAction.do_the_build()
	*-- release this so it can rebuild after testing
	buildAction = .NULL.
	CLEAR CLASS BuildAction
	RETURN llOK
ENDFUNC 

FUNCTION Build_In_Function
	LPARAMETERS tcOutputName, tnBuildAction, tlShowErrors, tlBuildNewGUIDs, toProject
	?"Call Depth:",PROGRAM(-1),PROGRAM(PROGRAM(-1))
	RETURN toProject.Build(tcOutputName, INT(tnBuildAction), .F., tlShowErrors, tlBuildNewGUIDs) 
ENDFUNC 

DEFINE CLASS BuildAction as Custom 
	FUNCTION do_the_build
		LOCAL ii, tcOutputName, tnBuildAction, tlShowErrors, tlBuildNewGUIDs, llOK
		tcOutputName = "C:\WORK\COMTESTVFPA\BIN\TESTCOM2.EXE"
		tnBuildAction = 3.00
		tlShowErrors = .T.
		tlBuildNewGUIDs = .F.
		FOR ii = 1 TO _vfp.Projects.Count
			IF "testcom.pjx" $ LOWER(_vfp.Projects.Item(ii).Name)
				?"Call Depth:",PROGRAM(-1),PROGRAM(PROGRAM(-1))
				llOK = Build_In_Function(tcOutputName, INT(tnBuildAction), tlShowErrors, tlBuildNewGUIDs, _vfp.Projects.Item(ii)) 
				*llOK = _vfp.Projects.Item(ii).Build(tcOutputName, INT(tnBuildAction), .F., tlShowErrors, tlBuildNewGUIDs) 
			ENDIF 
		NEXT 
		RETURN llOK
	ENDFUNC 
ENDDEFINE 

```

**Comment by DougHennig** [comment]
I'm not seeing that in the latest build:

![image](https://user-images.githubusercontent.com/12052409/115154733-ffcee680-a041-11eb-85ac-f7c5cc524236.png)

**Comment by DougHennig** [comment]
Very weird. Unfortunately, not a bug I can fix since it's a VFP bug. I suggest reporting it to Chen to see if he can fix it in VFP Advanced.

**Comment by Tracy-P** [comment]
What that test is about is building a project through an APP like you are doing.
The code I posted is the only PRG in the project that I build as an APP.
When processing through the APP in the current code as is, it returns `.T.`.
Change which line is commented in the Class function `do_the_build` to have it call the build on the project instead of passing it to a function and it returns `.F.`. 

I will reach out to Chen about it though.

**Comment by DougHennig** [comment]
I tested this in Project Explorer: I built a project to a multi-threaded DLL, a single-threaded DLL, and an EXE, in both VFP and VFPA. In all cases, the Build method of the project object returns .T.

**Comment by Tracy-P** [comment]
Did your OlePublic class have a Protected method in it?

The code I shared above will return .F. if the call to the Build method is in the Class, but not as it is in a Function.

It was pointed out to me by my coworker this issue was closed two years ago.  I came back to it because of the other issue I just reported about the Build type not being an INT causing a different problem. Which you quickly fixed, and I thank you.

**Comment by DougHennig** [comment]
I added a protected method to my OlePublic class, built it to a MT DLL using Project Explorer (the Build method returned .T.), and checked RegEdit: Foxruntime was properly set to VFPAT.DLL.

**Comment by Tracy-P** [comment]
It fails for me. Here is my example project.
https://github.com/Tracy-P/testcom

**Comment by DougHennig** [comment]
Thanks -- I was able to reproduce the error using your project. However, even when I move the Build command to a PRG, I still get a "Function argument value, type, or count is invalid" error in both VFP and VFPA. Then I tried to build it just using the VFP Project Manager (i.e. MODIFY PROJECT TestCom, click Build button). Same error, again both in VFP and VFPA. 

I reversed the order of the methods:

```
DEFINE CLASS mycomobject as Session OLEPUBLIC 
   
   PROCEDURE VisibleMethod
      RETURN THIS.HiddenMethod() + " via the VisibleMethod"
   ENDPROC 

   PROTECTED PROCEDURE HiddenMethod
      RETURN "From Hidden"
   ENDPROC 
ENDDEFINE
```

and now it builds fine using the Project Manager. I moved the call to toProject.Build to a PRG and it now builds in Project Explorer as well, but again only with the order of the methods reversed.

**Comment by Tracy-P** [comment]
I just tried that, still fails for me.
It has always worked building from the Project Manager. 
I'll look further tonight.
Thank you for looking at it again.

**Comment by Tracy-P** [comment]
Okay, I just downloaded the build you have from today. (2021-04-08)
I see that you are now calling a procedure in a prg from the class.
It doesn't matter which way I have the code organized in the OLEPUBLIC class. It is ALWAYS building correctly through PEX.

Thank you!

**Comment by Tracy-P** [comment]
You may want to check the project. I don't see the function in the Source.

**Comment by DougHennig** [comment]
Oops, forgot to add it to the repo. Done.
