### ISSUE TITLE
Key already exists

### ISSUE THREAD

**Issue by Steingo** [DougHennig/ProjectExplorer#168]
I thought I had an issue to report, but it has sort of devolved into an anomaly note.   For the past few days I was getting the following error whenever I started PE with my default solution:

Error #:	2062
Message: The specified Key already exists.
Code:	loCollection.Addfloltem, IcKey)
Line #:	83
Method:	projectengine.getdasses

If I told it to continue, it would finish loading and everything seemed to work fine.  I tried opening each of the 3 projects in Project Manager, thinking one of the project files might be corrupted, but they all appeared to be OK.   So then I pulled all the projects out of the solution - and found out PE won't open at all.  Next I put them back in one by one, thinking I'd identify which one was causing the problem.  But each time PE came up fine, even when I had everything back to the original configuration. 

So, as I said, an anomaly and everything seems to be back to normal.  If that changes I will let you know. 

--stein

I see that Phil reported a similar error but in a different context.  I don't think this was related..

**Comment by DougHennig** [comment]
That's a weird error because the GetClasses method specifically checks if the key exists in the collection before trying to add it.

Let me know if it happens again.
