### ISSUE TITLE
F2 for renaming files

### ISSUE THREAD

**Issue by Irwin1985** [DougHennig/ProjectExplorer#169]
Hi Doug,

How can I rename the files? In Native VFP Prject Explorer I do that by pressing F2 or Right Click PopUp.

Thanks!

![image](https://user-images.githubusercontent.com/8443227/59163896-2d54bb80-8acc-11e9-810a-b29158ad4049.png)

**Comment by DougHennig** [comment]
Click the Expand button in the toolbar and then enter the new name in the Name textbox.

**Comment by Irwin1985** [comment]
It was so easy! You even did it in the video.
Thanks!
