### ISSUE TITLE
oCategoryManager unknown element

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#171]
Hello Doug,
when I started the actual projectexplorer from June, the 21, i get an Error
oCategoryManager unknown element
![Error1](https://user-images.githubusercontent.com/29651009/60738936-48e2a300-9f60-11e9-9369-05c45a9291e3.jpg)
After pressing the break-command-button the debugger opens and show this:
![Error2](https://user-images.githubusercontent.com/29651009/60738978-70397000-9f60-11e9-966c-b5719b5fdf08.jpg)

Can you resolve this problem?

My last version of projectexplorer from february, the 13, works.
-- 
Hans-Peter Grözinger

**Comment by DougHennig** [comment]
Can you show me a screen shot of the call stack when this error occurs?

**Comment by HaPe4** [comment]
Please show here:
![callstack](https://user-images.githubusercontent.com/29651009/60820668-35267f00-a1a2-11e9-9fff-0d7cb95d4a16.jpg)
![callstack1](https://user-images.githubusercontent.com/29651009/60821473-e0840380-a1a3-11e9-8c5b-1206775a87d7.jpg)
![callstack2](https://user-images.githubusercontent.com/29651009/60821555-0dd0b180-a1a4-11e9-92be-d76a133abdc7.jpg)
System.app should be no problem, because by using the projectexplorer.app from february in the same path no error comes up.
