### ISSUE TITLE
Error when clicking Servers tab

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#172]
I was poking around at a single project solution and ran into the following error when clicking on the Servers page. I was in the Build Settings page and had made a small change to the copyright field. I then clicked on the Servers tab and got this error:

---------------------------
VFP9 SP2
---------------------------
Error #:     1925
Message:     Unknown member OPROJECT.
Code:        for each loServer in This.oProject.Servers foxobject
Line #:      19
Method:      projectsettings.getservers

Choose Yes to display the debugger, No to continue without the debugger, or Cancel to cancel execution
---------------------------
Yes   No   Cancel   
---------------------------

![image](https://user-images.githubusercontent.com/28717887/66584808-c87da080-eb53-11e9-9792-f12f2eb4215c.png)

**Comment by DougHennig** [comment]
Hi Richard.

I can't reproduce this. Looking at the code, I can't see where oProject would get set to null except when the Project Explorer is closed. Can you reproduce it?

Doug

**Comment by rikaye** [comment]
At the time I was able to get it to happen multiple times. I reset my environment and now the Server tab is coming up with no issues. I'll let you know if I can find the right set of conditions.
