### ISSUE TITLE
Local image reference in projectexplorerui.projectexplorerformtreeviewcontroller

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#174]
Whilst attempting to solve the Visual Diff issue I emailed directly to Doug, I found two references to images used for the shortcut menu which point to Doug's user folder. Not sure if this means I've got some out of date version of the source?

![pexdebug2](https://user-images.githubusercontent.com/28717887/66836391-3ac4fb00-ef2f-11e9-870d-ec5c71b14a95.png)

**Comment by DougHennig** [comment]
No harm done: since the images are built into the APP, VFP will use them rather than looking for the non-existent path. However, this is now fixed. Thanks.
