### ISSUE TITLE
Request:  change cursor or otherwise notify user that solution is being loaded.

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#175]
I've found that when loading my main project it can take few seconds but there is no visual indicator that the solution is still being loaded. Changing the mouse cursor to the hourglass pointer would be a useful hint that something is happening.

Thanks.

**Comment by DougHennig** [comment]
I added a WAIT WINDOW in the latest build

**Comment by rikaye** [comment]
I hit an error in PEx when I attempted to load a different solution while some unrelated source was open and wanted to bring this knock-on effect to your attention. The cursor had changed to an hourglass when I started the process of opening another solution. When I clicked Cancel in the error messagebox, the cursor did not change back to the pointer.

**Comment by DougHennig** [comment]
This sounds like a different issue, so please create a new issue with steps to reproduce. Thanks.
