### ISSUE TITLE
Mouse cursor does not change back to standard pointer when PEx throws an error

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#180]
Steps to reproduce:
Experience an error in PEx. :-) 

In my case, I had PEx open with one of my projects as well as the form designer with unsaved changes. The form was not part of the current solution open in PEx. I selected the menu option in PEx to open the solution in which this particular from was included. PEx didn't like that, presumably because it was attempting to check the status of the form I had open in the form designer but I didn't dig into the error. PEx raised its standard error dialog. I then clicked the Cancel option to stop the current code/method.

The mouse cursor remained in the hourglass state.

**Comment by DougHennig** [comment]
I removed the code setting the MousePointer to an hourglass because it stayed an hourglass under this and other conditions.
