### ISSUE TITLE
Error returning to PeX when exiting main program for a WWC application

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#181]
Hi Doug,

I'm in development on a WWC project. When I exit the WWC console, which is loaded by running the main prg from PeX, I get the following error dialog:

![image](https://user-images.githubusercontent.com/28717887/73289515-d3c00f00-41ca-11ea-8b98-939d930581a3.png)

I can continue and bypass the debugger but thought I should report it here. If you need more info, please let me know.

**Comment by rikaye** [comment]
And here's the code block from the debugger:

![image](https://user-images.githubusercontent.com/28717887/73289703-2bf71100-41cb-11ea-8eb6-012e814a44e7.png)

**Comment by DougHennig** [comment]
Not everything can be run from Project Explorer. For example, anything doing a CLEAR ALL will cause it to fail. In this case, you can see that llReturn is assigned a value from RunItem, so if llReturn doesn't exist, that means the calling code perhaps released it or did a CLEAR ALL. Not much I can do about that.

**Comment by rikaye** [comment]
Agreed, and I do think there's a CLEAR ALL situation here which is also attempting to get rid of the PeX object as well as llReturn. But a try..catch around that or even a vartype check could handle the exception more gracefully and just allow PeX to go away without throwing the error. In any case, this is not a significant issue. I just wanted to let you know I ran into something that raised an error.

**Comment by rschummer** [comment]
My initial thinking on this was to try a BeforeRunItem addin, but that is not likely going to help at all with a CLEAR ALL in the mix. I agree that the TRY...CATCH wrap around the code after the call to RunItem method would make it handle the potential problem more gracefully.

**Comment by DougHennig** [comment]
I can't necessarily use a TRY: see page 27 of the PDF for a discussion of the "Use TRY when running programs" option setting for an explanation. I'll add a check to see if llReturn exists.

**Comment by rikaye** [comment]
Thanks, Doug!
