### ISSUE TITLE
Mouse pointer not reset after opening solution

### ISSUE THREAD

**Issue by RickBorup** [DougHennig/ProjectExplorer#184]
When a solution is opened, the mouse pointer changes to the hourglass and remains in that state even after the solution finishes opening and the Project Explorer UI is displayed and ready for use. Project Explorer is being launched from the command window with 'DO path/to/projectexplorer.app'. The behavior is the same regardless of whether a solution file already exists or not, and affects _screen.mousepointer as well as the mouse pointer in the Project Explorer UI.

![image](https://user-images.githubusercontent.com/9992421/86312285-f924cf00-bbe7-11ea-828e-59ee4896ca42.png)

**Comment by DougHennig** [comment]
Fixed in the latest build.
