### ISSUE TITLE
Adding table

### ISSUE THREAD

**Issue by AnatolBazyukin** [DougHennig/ProjectExplorer#185]
Version 1.0.7488
When tables are added to the database, they are added to the free tables section.

**Comment by DougHennig** [comment]
If the database is selected in Project Explorer when you add the table, it is added to the database. I suspect you had the Free Tables node selected when you added the table.

**Comment by AnatolBazyukin** [comment]
A picture is worth a thousand words.
[Adding table.avi.zip](https://github.com/DougHennig/ProjectExplorer/files/5049569/Adding.table.avi.zip)

**Comment by DougHennig** [comment]
Choose Options from the Project Explorer menu and turn off Add and New Allow Any File Type.

Doug

**Comment by AnatolBazyukin** [comment]
This is somewhat unexpected. :)
