### ISSUE TITLE
Source control property checkbox state changed

### ISSUE THREAD

**Issue by rikaye** [DougHennig/ProjectExplorer#186]
Hi Doug,

I was doing some cleanup work on a project via pEX. This project is connected to a private git repo. I'm not sure how it happened but I noticed at one point I was no longer getting the scc-related context menu options. When I went into the solution properties the use version control box was no longer checked. I did make a change to some pf the project metadata including changing the icon, and I suspect that this was how that happened. I was able to check it again, and then point it at the proper folder for the associated repo so no harm, no foul but I thought I should pass this on.

**Comment by DougHennig** [comment]
Let me know if it happens again and if you can recall other things you do that may cause it.

**Comment by Tracy-P** [comment]
I have seen this behavior when the Project Explorer is opened a second time. The information in the slx file relating to what source control is connected is removed. 
Since my slx is in source, I just revert it.

**Comment by DougHennig** [comment]
Hi Tracy.

This should be fixed in the latest build.

Doug
