### ISSUE TITLE
FoxBin2Prg not found without Thor

### ISSUE THREAD

**Issue by s-s-a** [DougHennig/ProjectExplorer#189]
ProjectExplorer asks location of FoxBin2Prg at adding project to Source Control, but not run FoxBin2Prg wihout Thor.

**Comment by DougHennig** [comment]
The issue is fixed: when you turn on version control for a project, it will update the path in ProjectExplorerSettings.xml. To handle it for an existing project, edit ProjectExplorerSettings.xml and set the path attrribute to the correct location for FoxBin2PRG.
