### ISSUE TITLE
Autoexpand Tree

### ISSUE THREAD

**Issue by eselje** [DougHennig/ProjectExplorer#19]
It'd be efficient if the tree autoexpanded every time the category changed.

**Comment by eselje** [comment]
Rather than a menu item, can there be another tab for Solution Settings to go along with Project Settings and Build Settings? Then the Source Control settings that are currently under a menu item could be there instead, and you could have buttons for adding projects to the current solution, cleanup solution, et al.

**Comment by eselje** [comment]
I'd like to be able to customize what the Build button does, because sometimes I have my projects actually Built by a CI Server like Jenkins. It'd be cool if pushing the Build button could just call a script that instigates that build.

**Comment by eselje** [comment]
I'd like to tag multiple files w/o using a property filter, like by highlighting the files and right+clicking. e.g. I'd like to have all my graphics files tagged with 'Graphics'. 

I'd also prefer not to see the main grouping tag as a node when using custom tags, so e.g. if I'm looking at my Graphics tag I would see the files as the children, not "Other Files" as the first and only child of my tree.

**Comment by eselje** [comment]
If I have an existing project, is there an easy way to make it a part of a solution? Does that just happen automatically when I open the project in ProjExp (my hip name for this)?

**Comment by eselje** [comment]
It'd be efficient if labels, like parent class and path, were links so I can open/edit just by clicking.

**Comment by DougHennig** [comment]
It remembers which nodes are expanded for each tag. So once you've expanded them, they stay expanded, even through different sessions, until you collapse them again. I prefer that to auto-expanding because I rarely want all class libraries expanded, for example.

**Comment by eselje** [comment]
Ok, that's good too.
