### ISSUE TITLE
PEx and file not in the git repository

### ISSUE THREAD

**Issue by barryjaft** [DougHennig/ProjectExplorer#191]
PE shows files as "clean" which are not in git repository
![image](https://user-images.githubusercontent.com/51342646/109513951-73993d80-7a5a-11eb-8e0c-c46efc5d0c73.png)

**Comment by barryjaft** [comment]
even after removing it, it still shows as if it is in the repository.
![image](https://user-images.githubusercontent.com/51342646/109522409-1950aa80-7a63-11eb-91a7-af5228535005.png)

**Comment by DougHennig** [comment]
Hi Barry.

Project Explorer uses GIT STATUS --PORCELAIN to get the status of all files. If the file isn't listed as ?? Filename, then Project Explorer treats the file as clean. For some reason, Git isn't flagging those files properly for you.

Doug

**Comment by barryjaft** [comment]
thanks Doug.

PE shows the status of dirty files in Git properly. 
But i can not revert them or commit them without crashing.
![image](https://user-images.githubusercontent.com/51342646/109726846-36bb6c80-7b68-11eb-9b23-2fc4377c6d3c.png)

**Comment by DougHennig** [comment]
Unfortunately, "crashing" doesn't help me much. I need details such as the error message.

Doug

**Comment by barryjaft** [comment]
bad phrasing. VFP 9 was "Not Responding" for 2 1/2 hours until I ended the task.
Nothing you can do with that. I will close this

**Comment by barryjaft** [comment]
Thanks for being so responsive. I really appreciate it.
