### ISSUE TITLE
PE restart required after any change to Catagory or Tag

### ISSUE THREAD

**Issue by barryjaft** [DougHennig/ProjectExplorer#192]
very frustrating.
FYI - installed PE via Thor

**Comment by DougHennig** [comment]
Fixed in the latest build.

**Comment by barryjaft** [comment]
that is better i don't have to restart but i do have to collapse/expand the tree view to see the change

**Comment by DougHennig** [comment]
I'm not seeing that: as soon as I choose Yes to the "Assign child items" dialog (which doesn't show up in this video but did appear), the child items change.

https://user-images.githubusercontent.com/12052409/109552390-55056780-7a97-11eb-932b-cfb5cc0ad4e1.mp4
