### ISSUE TITLE
Not create  Solution.Xml for new project

### ISSUE THREAD

**Issue by s-s-a** [DougHennig/ProjectExplorer#193]
Step to reproduce:
1. Create a project.
2. Launch Project Explorer.
The CHOICE !!! Solution.Xml file dialog will appear 
There is nothing to select, when canceled, everything is closed. Solution.Xml is not generated.

**Comment by DougHennig** [comment]
As the documentation notes, when this dialog appears, choose Project from the Save as Type combobox, then select the project you want to create a solution for.
