### ISSUE TITLE
ProjectExplorer no run Foxbin2prg

### ISSUE THREAD

**Issue by s-s-a** [DougHennig/ProjectExplorer#194]
Menu item "Convert Binary to text" no runs Foxbin2prg .
Dialog with message "Since this is potentially destructive action, please confirm that you wish to proceed." opened, but foxbin2prg window not appears, file not creates, icon in tree changed to document not in CVS.

In previous version of Project Explolrer to fix this bug used path="D:\Work\ForGit\" attribute in projectexplorersettings.xml

**Comment by DougHennig** [comment]
This isn't a bug: Project Explorer needs to know where FoxBin2PRG is installed. By default, it tries to use Thor to determine the location, but if you don't have Thor installed, you can edit projectexplorersettings.xml and specify the path in the path attribute of the textconverter element.

**Comment by s-s-a** [comment]
I repeat:
**In previous version of Project Explolrer to fix this bug used path="D:\Work\ForGit" attribute in projectexplorersettings.xml**
But in current version this hook not work.

**Comment by s-s-a** [comment]
All files (ProjectExplorer.app, system.app, foxbin2prg.exe and projectexplorersettings.xml) in folder D:\Work\ForGit

**Comment by DougHennig** [comment]
Project Explorer needed FoxBin2PRG.prg rather than the EXE. That's fixed in the latest build.

**Comment by s-s-a** [comment]
I reopen this issue. Same simptoms. No Thor at all. All files in same place.

**Comment by s-s-a** [comment]
Oop's, ProjectExplorer version is 1.0.8120

**Comment by DougHennig** [comment]
I just tried it again without Thor and it works for me. Please attach ProjectExplorerSettings.xml here so I can see what you have the path attribute set to in this element:

```
<textconverter name="FoxBin2PRG" class="BinaryToTextConversionFoxBin2PRG" library="ProjectExplorerEngine.vcx" path="{execscript(_screen.cThorDispatcher, 'Thor_Proc_GetFoxBin2PrgFolder')}" />
```

Does the path you specify have either foxbin2prg.prg or foxbin2prg.exe in it?

**Comment by s-s-a** [comment]
<settings>
	<versioncontrol>
		<provider name="Mercurial" class="MercurialOperations" library="ProjectExplorerEngine.vcx" folder=".hg" />
		<provider name="Git" class="GitOperations" library="ProjectExplorerEngine.vcx" folder=".git" />
	</versioncontrol>
	<textconverters>
		<textconverter name="FoxBin2PRG" class="BinaryToTextConversionFoxBin2PRG" library="ProjectExplorerEngine.vcx" path="{execscript(_screen.cThorDispatcher, 'Thor_Proc_GetFoxBin2PrgFolder')}" />
		<textconverter name="TwoFox" class="BinaryToTextConversionTwoFox" library="ProjectExplorerEngine.vcx" path="" />
	</textconverters>
</settings>
 
The .ConverterPath contains {execscript(_screen.cThorDispatcher, 'Thor_Proc_GetFoxBin2PrgFolder')} at runtime.

**Comment by s-s-a** [comment]
Content of ProjectExplorerSettings.xml:
```
<settings>
	<versioncontrol>
		<provider name="Mercurial" class="MercurialOperations" library="ProjectExplorerEngine.vcx" folder=".hg" />
		<provider name="Git" class="GitOperations" library="ProjectExplorerEngine.vcx" folder=".git" />
	</versioncontrol>
	<textconverters>
		<textconverter name="FoxBin2PRG" class="BinaryToTextConversionFoxBin2PRG" library="ProjectExplorerEngine.vcx" path="{execscript(_screen.cThorDispatcher, 'Thor_Proc_GetFoxBin2PrgFolder')}" />
		<textconverter name="TwoFox" class="BinaryToTextConversionTwoFox" library="ProjectExplorerEngine.vcx" path="" />
	</textconverters>
</settings>
```

**Comment by s-s-a** [comment]
Oop's. WTF? XML text got to dev/nul?
XML exists in previous comment, but not visible?

**Comment by DougHennig** [comment]
Try using three reverse apostrophes before and after the text, like this:

```
some text
```

That being said, as I mentioned before, the path attribute has to be set to the path of the FoxBin2PRG program files. Using "{execscript(_screen.cThorDispatcher, 'Thor_Proc_GetFoxBin2PrgFolder')}" requires Thor.

**Comment by s-s-a** [comment]
I used old trick with direct set of path attibute. It works for a while.

"Try using three reverse apostrophes before and after the text"
Yes. it works as you can see above.

At last week PE asked for projectexplorersettingssource.xml. I don't know why.
