### ISSUE TITLE
Classlib serialized with class name for renamed class rather than classlib name (using Git)

### ISSUE THREAD

**Issue by DanLauer** [DougHennig/ProjectExplorer#195]
I have a classlib named swwdataars.vcx and a member class named swwitemcursoradapter. I select this class in the treeview, expand the window, and rename the class to swwitemcodecursoradapter. Upon saving the change, Project Explorer prompts for a commit message. I enter "Renamed class" and say OK. Project Explorer then serializes the classlib with FoxBin2Prg, but the resultant serialization is called swwitemcodecursoradapter.vc2, rather than swwdataars.vc2. Since this .vc2 file is not in the Git repository, it is not committed, and the file shows as an untracked, uncommitted change.

Any subsequent change to the class works as expected, and the name change ends up being tracked, but not with an explicit commit, as expected at the time of the name change.

**Comment by DougHennig** [comment]
Try the latest build; I believe it fixes this bug.

**Comment by DougHennig** [comment]
Oops, it wasn't fixed. It is now in a build dated 04/13/2021.

**Comment by DanLauer** [comment]
Awesome, thanks.
