### ISSUE TITLE
Build MTDLL assigns VFP*R.DLL in Registry

### ISSUE THREAD

**Issue by Tracy-P** [DougHennig/ProjectExplorer#197]
Okay, I'm testing VFP Advanced and working with Project Explorer.
I have two projects. An EXE and a MTDLL. 
When I compile the MTDLL, the tnBuildAction in ProjectOperations.BuildProject is 5.00
When I `_vfp.projects.item("mtdllproject").Build("bin\testcom.dll",5.00, .T., .T., .F.)` the behavior is the same.

I find the CLSID for the testcom.testcom in the Registry, and look at the FoxRuntime and find VFPAR.DLL
![image](https://user-images.githubusercontent.com/47571263/114791300-47a8f180-9d54-11eb-991c-6c69a6e21138.png)

When I `_vfp.projects.item("mtdllproject").Build("bin\testcom.dll",5, .T., .T., .F.)` the behavior is the expected.
![image](https://user-images.githubusercontent.com/47571263/114791331-52fc1d00-9d54-11eb-8164-50026d8f9633.png)

**Comment by Tracy-P** [comment]
The behavior is in VFP 9 as well. I was finally able to get that tested today.

**Comment by DougHennig** [comment]
Fixed in the latest build. Thanks for the heads-up.
