### ISSUE TITLE
Could the Revision History function use gitk?

### ISSUE THREAD

**Issue by Tracy-P** [DougHennig/ProjectExplorer#198]
It's possible to start gitk showing the history of just one file.
Currently you are using `git log --follow -p -- <file>`

![image](https://user-images.githubusercontent.com/47571263/116344404-2adcd700-a7b4-11eb-85ca-219e9f983d96.png)

I find it easier to use the `gitk -- <file>`

![image](https://user-images.githubusercontent.com/47571263/116344578-7beccb00-a7b4-11eb-80d5-87658b56e6c0.png)

**Comment by DougHennig** [comment]
Thanks -- implemented in the latest build.
