### ISSUE TITLE
Add "Compile" command on the context menu when right-clicking on a PRG file in TreeView

### ISSUE THREAD

**Issue by mattslay** [DougHennig/ProjectExplorer#199]
[Feature Request]

Add "Compile" command on the context menu when right-clicking on a PRG file in TreeView

![Snag_133c9750](https://user-images.githubusercontent.com/309016/117359236-bde4d380-ae7c-11eb-88f3-7a8b85da961a.png)

**Comment by DougHennig** [comment]
You can do that using an add-in. See AddPackToShortcutMenu.prg in the Addins folder for an example.

**Comment by mattslay** [comment]
Thanks for this info Doug.
