### ISSUE TITLE
Incorrect check SourceTrree is installed

### ISSUE THREAD

**Issue by s-s-a** [DougHennig/ProjectExplorer#200]
ProjectExplorer use HKEY_CLASSES_ROOT\sourcetree\shell\open\command registry key to check SourceTree is instaled. But SourceTree deinstalling process not deletes this key. 
Visual Diff, Repository browser and Revision history do nothing after deinstalling SourceTree.

**Comment by DougHennig** [comment]
Fixed in the latest release.
