### ISSUE TITLE
Get a list of changes of incoming merge only

### ISSUE THREAD

**Issue by Tracy-P** [DougHennig/ProjectExplorer#202]
When you request a list of files from origin/<branch> you are using the syntax
`git diff --name only origin/master`

There is a slight tweak you can add to this command to only get a list of files that have changed on the remote.
`git diff --name only ...origin/master`

The three dots are important.

I am currently working on a UI update of a large project (over 500 forms). Two of us are touching 5 or more files each day. Our work flow has us `pull` before we `push` our changes. With the current syntax, the process updates each of the forms I updated as well as the forms updated by my teammate.  The suggested tweak will only run FoxBin2Prg on the files coming from the remote. 

Additionally, there may not be any updates on the remote, and each file is still processed by FoxBin2Prg.

Thank you,
Tracy

**Comment by DougHennig** [comment]
Thanks, Tracey. Fixed in the latest build.
