### ISSUE TITLE
Wrong file highlighted after a delete

### ISSUE THREAD

**Issue by Tracy-P** [DougHennig/ProjectExplorer#205]
Cleaning up a project we are removing files. The project explorer changes the highlighted file to the one below. Internally a different file is highlighted. 

As an example,  I modified a class in a library. Then switched to the forms group. I selected and deleted a form. Then I double clicked the highlighted form and the class browser opened.  I closed the browser and double clicked the form again. Same behavior. 

Earlier today my teammate was deleting bmp and msk files. He had just edited a class. Then switched to the other group selected and deleted the bmp. Since the msk was selected he deleted it. An error occurred. It also deleted the class library he last edited. Thankfully using git we were able to revert it back.

Error #:     1924
Message:     LOITEM is not an object.
Code:        This.oItem                 = loItem.Clone()
Line #:      42
Method:      projectexplorerform_62J12HJ51.displayproperties

**Comment by DougHennig** [comment]
Thanks for the detailed steps to reproduce. Fixed in the latest build.
