### ISSUE TITLE
Committing binary files, no text equivalents

### ISSUE THREAD

**Issue by barryjaft** [DougHennig/ProjectExplorer#206]
when committing changes in my class libraries (for example) to GIT, only the vcx is committed and subsequently pushed.

**Comment by Tracy-P** [comment]
I saw this behavior with Visual Source Safe in the past. It was like the only thing that changed was the timestamp in the VCX and not changes to the VCT happened. 
If you deleted the code out of a method or deleted a class completely. The pointer to the records in the VCT would have been zeroed/nulled. No change would have happened in the VCT. The VCT may change after a compile.

**Comment by barryjaft** [comment]
thanks, Tracy for the quick response. I have seen that in VSS as well. Not being very clever with GIT, I am at at a stand still. I can't push any changes to my repository because the tip of my current branch is behind its remote counterpart. If i do a GIT PULL i am going to loose many other changes that are still outstanding. Do you have any sage advice?

**Comment by barryjaft** [comment]
compiled my class library. checked git gui before hand both file show as needing commitment. committed from Project Explorer and then refreshed git gui. sure enough the vcx was committed but not the memo file.

**Comment by barryjaft** [comment]
so far the only value the git integration to me is that i can see which files are dirty in the project explorer.

**Comment by Tracy-P** [comment]
My team does not store the binaries in git. Using FoxBin2Prg does a good job. Sometimes the git Merge is odd when two team members have modified a library or form. So we check them from time to time.

**Comment by barryjaft** [comment]
yes well the project i inherited has always used binary. i am very uncomfortable switching gears in the middle of the stream. especially with my plebeian knowledge of GIT.

**Comment by Tracy-P** [comment]
You may have found a problem with Project Explorer integration.
You can use git gui to commit the VCT. There is also a "Amend Last Commit" if you haven't committed anything after the VCX was committed.

**Comment by barryjaft** [comment]
i like git gui. heck of a lot better than git bash.
thanks for all your help
