### ISSUE TITLE
Focus when returning to Project Explorer from outside VFP

### ISSUE THREAD

**Issue by Tracy-P** [DougHennig/ProjectExplorer#207]
As my workflow is regularly interrupted, I go to a different Windows application. When I return to VFP and click directly on the tree in Project Explorer the item I clicked on gets a gray focus. I then need to click it again to get the blue focus allowing me to type to get back to the form/class/prg I'm needing to open.

This doesn't happen every time. It happens enough though that if I don't catch it my typing has toggled an item to be excluded from the project. I do not have the extended pane open and this still happens.

The first time I extend the pane, or the focus was in the extended pane when I leave VFP, then click back on an item, it remains gray.

**Comment by DougHennig** [comment]
I haven't seen that but will keep an eye out for it.
