### ISSUE TITLE
Branch name problem

### ISSUE THREAD

**Issue by mauricioulla** [DougHennig/ProjectExplorer#208]
Hi!

We are trying to use Project Explorer over MS-DevOps SERVER 2020 with a Git repository.
DevOps creates the initial Branch with the name MAIN instead MASTER (Git default).

We have about 20 VFP's projects as a part a larger project that include several Visual Studio projects and Solution, all of them in the same DevOps Project and Git repository, so change the repository name its'n an option.

We get the following exception when "Update from Remote Repository".

![image](https://user-images.githubusercontent.com/44946773/128913487-a4816a3f-2896-4394-a960-21300f24947f.png)

Debuging the code we think that we found the issue in GitOperations Class, UpdateFromRemoteInternal() method:
![image](https://user-images.githubusercontent.com/44946773/128914515-f58b0cfc-aaa6-4719-99cd-e4833eaa5600.png)

**Comment by DougHennig** [comment]
This error is actually occurring in FoxBin2PRG. Note the path for the configuration file in the error message. Does that file exist?

**Comment by mauricioulla** [comment]
Yes, does exist.
![image](https://user-images.githubusercontent.com/44946773/129959837-11742370-e733-4caa-80f7-63a0ce16dc1a.png)

And this is its content:

> DBF_Conversion_Support:8

**Comment by DougHennig** [comment]
Do you have the latest version of FoxBin2PRG?

**Comment by mauricioulla** [comment]
Yes I guess!
![image](https://user-images.githubusercontent.com/44946773/130248233-8e20049a-c97c-4bad-9653-1bcda249dbcb.png)

**Comment by DougHennig** [comment]
In that case, I am not sure why you are getting that error. Perhaps add a SET STEP ON to the EvaluateConfiguration method in FoxBin2PRG, rebuild the EXE, and try again to see if you can see what's causing the error.

**Comment by mauricioulla** [comment]
By now I rebuilt ProjectExplorer with a little change. I have replaced the string literal "origin/master" with "origin/main"  in UpdateFromRemoteInternal() method of the GitOperations Class, and It is working fine.

But I'll try what you suggest, because you make me realize that my fix is the poorest.

**Comment by mauricioulla** [comment]
I has resolved the issue, It was the path....

I was invoking ProjectExplorer from a path diferent from solution path (*.slx).

**I get the issue:**
SET DEFAULT TO  "C:\Path_A"
DO ProjectExplorer.app WITH "C:\Path_B\MySolution.slx"

**Works fine:**
SET DEFAULT TO  "C:\Path_A"
DO ProjectExplorer.app WITH "C:\Path_A\MySolution.slx"
