### ISSUE TITLE
Customize build function

### ISSUE THREAD

**Issue by DougHennig** [DougHennig/ProjectExplorer#21]
I'd like to be able to customize what the Build button does, because sometimes I have my projects actually Built by a CI Server like Jenkins. It'd be cool if pushing the Build button could just call a script that instigates that build (submitted by Eric Selje).

**Comment by DougHennig** [comment]
Can you do that with a BeforeBuild or AfterBuild addin?

**Comment by eselje** [comment]
Maybe, yes, though that would require a project hook. I'd have to recollect whether one can suppress the default Build action with BeforeBuild so the default action doesn't actually fire.

**Comment by DougHennig** [comment]
No project hook required. See the Addins section of ProjectExplorer.pdf. Basically, you'll create a PRG in the addins folder that handles the AfterBuildProject event and does whatever is necessary. You could also handle BeforeBuildProject and then return 1 meaning the event was handled and succeeded but you don't want the normal processing.
