### ISSUE TITLE
tags with special characters

### ISSUE THREAD

**Issue by NigelGomm** [DougHennig/ProjectExplorer#211]
Doug,
got myself into a world of trouble by adding tags with spaces, periods etc - anything that couldn't be in an object name.
so added
THIS.VALUE = CHRTRAN(THIS.VALUE,[. {}/;:\"')(*&^%$#@!|-+=],[])
THIS.VALUE = CHRTRAN(THIS.VALUE,"[]","")
at the top of txtTag.lostfocus in projectexplorertageditor

Haven't tried with categories yet.

nigel

**Comment by DougHennig** [comment]
Spaces in tags work for me, but there is an issue with custom tags: they only work when the parent for an object also has that tag. For example, I created a tag named "Test Me" and used that tag for a class. When I choose "Test Me" from the tag filter combo box, the class doesn't show up. However, if I use that tag for the class library containing the class, then it does.

Spaces in categories work fine.

**Comment by Woody-Soft** [comment]
Maybe only allow tags where ISALPHA() = .T. instead of checking for an ever-growing list of special chars?

**Comment by DougHennig** [comment]
Fixed in the latest build: special characters are allowed but no longer cause an error.
