### ISSUE TITLE
Remove file dialog presents Abort/Retry/Ignore as options

### ISSUE THREAD

**Issue by DanLauer** [DougHennig/ProjectExplorer#213]
Do you walk to work or carry your lunch?

![image](https://user-images.githubusercontent.com/2616544/152255044-d6965e14-4a3e-44c5-9f9f-63ece11ac74e.png)

**Comment by DougHennig** [comment]
It displays Remove, Delete, and Cancel for me. I use Cesar Chalom's MessageBoxExtended to customize the messagebox buttons but it must be failing on your system for some reason.

**Comment by KevinRagsdale** [comment]
I ran into a similar issue today when selecting Convert Binary to Text from the treeview shortcut menu.  It was supposed to prompt with All Files and Project Only, but instead prompted with Yes and No buttons.  Recompiling the Project Explorer app fixed the issue for me.
