### ISSUE TITLE
Double clicking a text file errors if there are spaces in the path

### ISSUE THREAD

**Issue by DanLauer** [DougHennig/ProjectExplorer#214]
## 📝 Provide detailed reproduction steps (if any)

Running 1.0.7773

1. Add a text file to the project from a folder that has spaces in the name, or where a parent folder has spaces in the name.
2. Double click the file to open for edit.

### ✔️ Expected result

Should open the file for edit without error.

### ❌ Actual result

This error occurs:
![image](https://user-images.githubusercontent.com/2616544/173703461-9c86cf59-c510-4319-a2e3-0ca9597188c0.png)
followed by this error:
![image](https://user-images.githubusercontent.com/2616544/173703416-95366ce9-56fd-44fa-a805-e97d7ad00f26.png)

**Comment by DanLauer** [comment]
.PRG files with spaces in the path work just fine.

**Comment by DougHennig** [comment]
It works for me in the latest build (1.0.8120).

**Comment by DanLauer** [comment]
I updated and the problem is solved!
