### ISSUE TITLE
"All" treeview doesn't refresh automatically after adding files

### ISSUE THREAD

**Issue by DanLauer** [DougHennig/ProjectExplorer#215]
This is a confusing annoyance to me...not a crippling bug at all.

## 📝 Provide detailed reproduction steps (if any)

Running 1.0.7773

1. Add a file to the project
2. Switch back to the _All_ view

### ✔️ Expected result

Added file should be displayed in both the file type view and the _All_ view

### ❌ Actual result

Upon adding a file to the project, the treeview switches to the view for the file type added, and the file is displayed as expected. Upon switching back to the _All_ view, the file is missing until Project Explorer is closed and re-opened, or _Refresh_ is run from the treeview's context menu.

**Comment by DougHennig** [comment]
Fixed in a new build: 1.0.8201, released 06/15/2022.
