### ISSUE TITLE
Problem with the Home path of the Projects

### ISSUE THREAD

**Issue by DanielCarlos231** [DougHennig/ProjectExplorer#218]
I have found a situation that hapens when the projects Home is in a diffent folder from the current folder...
The foxpro cannot find any file that is being referenced in code, because os the current path.
I foud a work arround, which was resetting the Default Path every time I selected a project, I added that functionatlity to the APP, so I wouldn't have to do it manually.
 I had to add do the destroy event a reset of the real Default PATH, because once I close the APP, it reopen it, it would only show the last project on the tree view, because of the change in the Default PATH.
 After I did those 2 changes, my projects would run with no errors.
 I just wanna report this situation, so that maybe it could benefit you in any way.

**Comment by DougHennig** [comment]
[SetCurDirOnProjectOpen.txt](https://github.com/DougHennig/ProjectExplorer/files/10440234/SetCurDirOnProjectOpen.txt)
You can do that with an add-in. Download the attached file, rename it to have a PRG extension, and drop it into the Addins subdirectory of the folder you installed Project Explorer in. From now on, when you open a solution, it will automatically change to that solution's folder.
