### ISSUE TITLE
VFP hangs after component save/close if opened from Project Explorer

### ISSUE THREAD

**Issue by DanLauer** [DougHennig/ProjectExplorer#219]
## 📝 Provide detailed reproduction steps (if any)

1. Open a component from Project Explorer.
2. Make changes, save and close the component.
3. VFP hangs (not responding) indefinitely. No way out but to kill the task.

### ✔️ Expected result

Should save, update the source control status in Project Explorer, and return control to the IDE.

### ❌ Actual result

Hangety hang hang.

**Comment by DanLauer** [comment]
I think this might be a Git issue, but I can't figure out what to check or change. I'm on Git 2.39.1.

**Comment by DougHennig** [comment]
I do this 100 times a day, so I don't think it's a Project Explorer bug. You may have to trace the code in the AfterEditItem method of the ProjectExplorerForm class in ProjectExplorerUI.vcx to see where it's hanging.

**Comment by DanLauer** [comment]
Yeah I've done it for years too. I don't understand what changed. I'll trace the code and report back.

**Comment by DanLauer** [comment]
OK I found this.

In the _.runcommand()_ of the _gitoperations_ class in _projectExplorerEngine.vcx_, this code block is looping infinitely:

```
		do while occurs(lcPrompt, lcResponse) < 2
			&& wait until the command prompt appears twice: once for the
			&& initial prompt and then again after the command has finished
			Sleep(1000)
			lcCurrResponse = loCmd.GetResponse()
			if not empty(lcCurrResponse)
				lcResponse = lcResponse + lcCurrResponse
			endif not empty(lcCurrResponse)
		enddo while occurs(lcPrompt, lcResponse) < 2
```

It's happening because _lcPrompt_ is `"C:\CODE\STOREPORTER>"` and _lcResponse_ is:

```
"Microsoft Windows [Version 10.0.22621.1265]
(c) Microsoft Corporation. All rights reserved.

C:\Code\storePorter>git commit --file "C:\Code\storePorter\commit.txt" "C:\Code\storePorter\swlibrary\prgs\a2lines.prg"
error: pathspec 'C:\Code\storePorter\swlibrary\prgs\a2lines.prg' did not match any file(s) known to git

C:\Code\storePorter>"
```

The case of _lcPrompt_ and the actual prompt in _lcResponse_ don't match so it'll just loop.

There's obviously an error in the Git response too, but that's not what's causing the hang.

I changed the code to this:
```
		* 02/17/23:DDL> 		
		* do while occurs(lcPrompt, lcResponse) < 2
		 do while occurs(lower(lcPrompt), lower(lcResponse)) < 2
			&& wait until the command prompt appears twice: once for the
			&& initial prompt and then again after the command has finished
			Sleep(1000)
			lcCurrResponse = loCmd.GetResponse()
			if not empty(lcCurrResponse)
				lcResponse = lcResponse + lcCurrResponse
			endif not empty(lcCurrResponse)
		enddo while occurs(lower(lcPrompt), lower(lcResponse)) < 2
		* enddo while occurs(lcPrompt, lcResponse) < 2
		* 02/17/23:DDL<
```

This solves the looping problem. Thoughts?

**Comment by DougHennig** [comment]
Thanks, Dan. I'll make the same change.
