### ISSUE TITLE
Edit MPR files from Project Explorer treeview

### ISSUE THREAD

**Issue by RickBorup** [DougHennig/ProjectExplorer#220]
I'm working on a project where the developers used hand-coded MPR files that need to be edited like PRGs. The MPR files were added to the Code tab in the VFP Project Manager. In the Project Manager, double-clicking on an MPR file or selecting it and clicking Modify opens the file in the code editor. 

In Project Explorer, the MPR files show up as expected under 'Programs' in the Code node of the treeview. However, nothing happens when you double-click on one (with Options | Project double-click action set to 'Modify selected file') or select it and click the 'Modify the selected item' icon on the toolbar.

Expected behavior: the MPR file opens in the code editor

Observed behavior: nothing happens

**Comment by DougHennig** [comment]
This is actually a VFP issue. Nothing happens when you run this code:

lofile = _vfp.activeproject.files('Path for mpr file')
lofile.modify(lofile)

That being said, it's now handled in the latest build.
