### ISSUE TITLE
Treeview with focus and user nonmodal desktop forms

### ISSUE THREAD

**Issue by klepetox** [DougHennig/ProjectExplorer#221]
## 📝 Provide detailed reproduction steps (if any)

When any node in treeview has focus (is blue), then any user defined forms with desktop=.t. are inaccessible (click on any buttons is not possible).

✔️ Expected result - nonmodal desktop windows are accessible.

❌ Actual result - nonmodal desktop windows are inaccessible. 

I'm using any working forms with buttons on the second monitor (must be desktop=.t.) and when Project Explorer is active window with blue node in treeview, I cannot work with these forms. When node is not blue (no focus, even form is active) desktop forms work properly.

**Comment by DougHennig** [comment]
Click the title bar of the form to activate it, then you can use it.
