### ISSUE TITLE
Tags and categories in Programs section are lost

### ISSUE THREAD

**Issue by klepetox** [DougHennig/ProjectExplorer#222]
I set tags and categories in Programs, Forms, Classes... sections. Everything is OK. But when I rebuild project outside Project Explorer (command window, menu) and run Project Explorer again, all tags and categories in section Programs are lost (Forms and others seems to be untouched).

**Comment by DougHennig** [comment]
Project Explorer stores an ID in the DevInfo memo in the PJX file and uses that to identify an object in the meta data table where tags and categories are stored. When you build the project in Project Explorer, those values are preserved. However, when you build using the Project Manager or BUILD command, they are blanked for some types of records (programs, tables, menus, etc.) but not all. Unfortunately, there isn't a good alternative place to store the ID; the User memo may be used for something else so I didn't want to disturb it.

The solution is to build the project using Project Explorer.
