### ISSUE TITLE
Recall docked position from last run

### ISSUE THREAD

**Issue by DanLauer** [DougHennig/ProjectExplorer#223]
## 📝 Provide a description of the new feature

On my laptop it works best for me to run ProjExp as a dockable window and dock to the left side of the VFP IDE window. Every time I close and reopen ProjExp, I have to re-dock. Since I scale my display at 125%, docking stuff in VFP is annoyingly difficult. I would love if ProjExp would remember and restore it's dock position from session to session.

_What is the expected behavior of the proposed feature?  What is the scenario this would be used?_

If I was docked in the last session, start docked in the same position. If was not docked in the last session, start undocked.
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by DougHennig** [comment]
Added this feature in the latest build.

**Comment by DanLauer** [comment]
Awesome!

Daniel Lauer
CEO & Chief Architect

StorePorter | it's web store genius

(888) 765-SYNC x101 | Direct: (208) 416-6101 | Fax: (208) 714-4036

( http://www.storeporter.com/ ) ( http://www.facebook.com/storeporter ) ( http://twitter.com/storeporter )
