### ISSUE TITLE
MRU

### ISSUE THREAD

**Issue by eselje** [DougHennig/ProjectExplorer#25]
I tend to modify the same few files over and over. It'd be great if there was a "Most Recently Modified" list I could use to easily find and modify the most recent files I've changed.

**Comment by DougHennig** [comment]
You can do that a couple of ways now:

* Set the Category for the ones you edit the most often (such as red, which you can rename in the Category Editor as "Most Often", for example), then set a filter on category is red.

* Create a filter on ttod(Item.LastModified) < date() - 7 to give you those items modified in the last week.

**Comment by eselje** [comment]
This works perfectly, thanks!
