### ISSUE TITLE
Cannot clear the object

### ISSUE THREAD

**Issue by eselje** [DougHennig/ProjectExplorer#26]
After doing a Build with Run after Build checked, I get this

Project Explorer

The application could not be run after it was buildt. Te error message is:

Cannot clear the object PROJECTEXPLORERFORM_4XQ0IEOKA because it is in use.

This seems to be repeatable.

**Comment by DougHennig** [comment]
Does your application have a CLEAR ALL in it? That would be a problem because Project Explorer ran your app thus it's still executing so it can't be cleared.

**Comment by eselje** [comment]
It does. Is the Project Explorer a property of _Screen, or can it be so it doesn't go away when a CLEAR ALL is issues? (I suppose I could look at the source code eh?)

**Comment by DougHennig** [comment]
Because there can be more than one instance of Project Explorer open, there's an oProjectExplorers member of _SCREEN that's a collection. Unfortunately, CLEAR ALL nukes that member.
