### ISSUE TITLE
Error # 1733: Class definition PROJECTITEMRELATION is not found

### ISSUE THREAD

**Issue by RickBorup** [DougHennig/ProjectExplorer#27]
Error 1733 'Class definition PROJECTITEMRELATION is not found' occurs in projectengine.getdatabaseitems method when selecting the PJX file for first-time use in Project Explorer. The project file contains a DBC that has table relations. 

![2017-06-09_callstack](https://user-images.githubusercontent.com/9992421/26989092-5be89e02-4d17-11e7-9331-4655106a2fec.png)

![2017-06-09_errormsg](https://user-images.githubusercontent.com/9992421/26989091-5be73954-4d17-11e7-8063-8050042a8aaf.png)

![2017-06-09_tracewindow](https://user-images.githubusercontent.com/9992421/26989093-5becbfa0-4d17-11e7-957a-b7ac2ea9c963.png)

![2017-06-09_watchwindow](https://user-images.githubusercontent.com/9992421/26989090-5be726e4-4d17-11e7-8b8e-70040c5bd3b7.png)

**Comment by DougHennig** [comment]
Fixed in latest commit
