### ISSUE TITLE
WhichOne

### ISSUE THREAD

**Issue by eselje** [DougHennig/ProjectExplorer#28]
Every once in a while my project won't build, but doesn't give me a good indication why. I've turned to using a utility written by Ted Roche / Barb Peisch called "WhichOne" that essentially compiles each component of the project one file at a time, wrapped in an error handler.

It'd be pretty sweet if Project Explorer could integrate this into a "Debug Build" option, either under that Build dropdown or a checkbox o nthe "Build Settings" tab.

**Comment by DougHennig** [comment]
Can you send me a copy of that utility? Thanks.

**Comment by eselje** [comment]
Here you go...

https://www.dropbox.com/s/vi37xjzflznehfv/WhichOne.prg?dl=0

**Comment by DougHennig** [comment]
I've added this: whenever you build with Recompile All Files checked, it manually compiles the files and displays a message about any that fail.

**Comment by DougHennig** [comment]
Thanks for the suggestion and the code!

**Comment by DougHennig** [comment]
I've implemented this in the latest build.

**Comment by eselje** [comment]
Very cool - thanks!
