### ISSUE TITLE
Project with bad timestamp kills opening of project.

### ISSUE THREAD

**Issue by psherwood** [DougHennig/ProjectExplorer#30]
Some of my projects have bad timestamps on entries for some reason. To get around this I added this code to the getdatetimefromtimestamp.prg code.

if empty(tiStamp) or vartype(tiStamp) <> 'N' **OR tiStamp < 500000**
	return {/:}
endif empty(tiStamp) ...

Then after all the bit shifting...

`* Check for valid parameters for datetime
IF NOT BETWEEN(lnYear,1980,YEAR(DATE()))
   lnYear = 1980
ENDIF
IF NOT BETWEEN(lnMonth,1,12)
   lnmonth = 1
ENDIF
IF NOT BETWEEN(lnDay,1,31)
   lnDay = 1
ENDIF
IF NOT BETWEEN(lnHour,1,24)
   lnHour = 12
ENDIF
IF NOT BETWEEN(lnMinute,0,59)
   lnMinute = 1
ENDIF
IF NOT BETWEEN(lnSecond,0,60)
   lnSecond = 0
ENDIF 

return datetime(lnYear, lnMonth, lnDay, lnHour, lnMinute, lnSecond)
`

**Comment by DougHennig** [comment]
Hi Phil.

Thanks for the code. Implemented.

Doug
