### ISSUE TITLE
Get error LOFILE is not object when trying to add XFRX.FXP to project

### ISSUE THREAD

**Issue by psherwood** [DougHennig/ProjectExplorer#32]
I downloaded the latest version and it still won't let me add an .fxp file. I've attached a screenshot of the error.
![image](https://user-images.githubusercontent.com/1342276/31136460-4f751e50-a836-11e7-8ac0-3436fd3649b2.png)

I went into debug and the problem is that when toProject.Files.Add(tcFile) is called, it doesn't return anything.  I tried doing a set step on in front of it, but it just skipped over that statement.
![image](https://user-images.githubusercontent.com/1342276/31136507-778ca34a-a836-11e7-93c9-54965e604b64.png)

-Phil

**Comment by DougHennig** [comment]
When I tested this, I chose a file that had a matching PRG. I thought it worked but in hindsight it actually added the PRG not the FXP to the project. I tried it again just now with an FXP that doesn't have a matching PRG and see what you mean. It looks like a bug in the Add method of the Project.Files collection: calling it with an FXP returns null and the file isn't added to the project. I'm not sure it's fixable. In the meantime, add the FXP to the project using the Project Manager and it'll show up in Project Explorer.
