### ISSUE TITLE
Allow ProjectExplorer window to be dockable

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#33]
It would be nice if there was at least an option to make the ProjectExplorer window dockable. Not only does this allow the window to be dragged outside of the VFP IDE (like the Desktop = .T. option), but it also allows the window to be tab-docked with other VFP windows like the Property Sheet and Document View, or with other add-ons like the Data Explorer or PEM Editor.

**Comment by DougHennig** [comment]
Thanks for the suggestion, Added in the latest build.
