### ISSUE TITLE
Assign Tags to Items is calling FoxBin2Prg for every item

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#35]
I had ProjectExplorer _Version Control Properties_ configured to use version control, with both binary and text files included in version control. The provider was set to Git, but I don't think that setting matters. When I ran the _Assign Tags to Items_ tool, FoxBin2Prg was being called for every item being tagged, which seems unnecessary, and made the tagging process really slow. I say that FoxBin2Prg was running for every **item**, because when the .DBC was being processed, FoxBin2Prg was being called for every table, field, index, etc., of that DBC.

**Comment by DougHennig** [comment]
Fixed in the latest build.
