### ISSUE TITLE
Project Explorer window is always a Desktop window

### ISSUE THREAD

**Issue by RickBorup** [DougHennig/ProjectExplorer#38]
The 'Window has Desktop turned on' check box shows as unmarked in the Options dialog, but the Project Explorer window behaves as if it's a Desktop window - i.e, the Project Explorer window can be moved outside of the VFP main window even if the 'Window has Desktop turned on' check box is unmarked. Related: if you mark the 'Window has Desktop turned on' check box in Options and click OK, Project Explorer does not remember the change. (Project Explorer 1.0.6500)

**Comment by DougHennig** [comment]
Do you have Dockable turned on in the Options dialog? If so, it can be moved outside the VFP window.

It does remember the change, but you have to close Project Explorer and reopen it for the setting to take effect since those window changes can't be done at runtime but require using a different class for the form.

**Comment by RickBorup** [comment]
Yes, Dockable was turned on. I think the confusion is that when the Dockable check box is marked and the 'Window has Desktop turned on' check box is unmarked, marking the 'Window has Desktop turned on' check box disables the Dockable check box but does not clear it. The next time Project Explorer is launched, the Dockable check box is still marked and the 'Window has Desktop turned on' check box is not marked, but at that point, the window behaves as if Desktop = .T. and at the same time it's still dockable. I can email you detailed steps to reproduce this, please let me know if you want them.

**Comment by DougHennig** [comment]
Thanks for the details -- fixed in the latest build.
