### ISSUE TITLE
Error 1683

### ISSUE THREAD

**Issue by regy79** [DougHennig/ProjectExplorer#39]
I keep getting error 1683 Index Tag Not Found, after I select the project

I tried once and it worked perfect. But the second time I opened it, the error happened and won't go off even though I delete the folder and run it again.

**Comment by regy79** [comment]
Method: projectengine.getmetadataforitem

**Comment by DougHennig** [comment]
It looks like the KEY tag for the meta data table (named Project_Metadata.dbf, where Project is the name of your project file) wasn't created or was deleted. Try this:

- Edit the ProjectEngine class in ProjectExplorerEngine.vcx and add SET STEP ON before the TRY statement in the CreateMetaData method. Build ProjectExplorer.app
- Delete Project_Metadata.* in your project folder
- Open the project with Project Explorer

As you trace the code in CreateMetaData, does code in the CATCH block execute? If so, what's the error message?

**Comment by DougHennig** [comment]
Just checking to see if you have had a chance to try these steps.
