### ISSUE TITLE
Selecting Version Control properties throws an error

### ISSUE THREAD

**Issue by paulmrozowski** [DougHennig/ProjectExplorer#4]
If you don't select the folder where FoxBin2Prg is located (and don't select the EXE), then selection Version Control Options from the menu, it fails with the following:

---------------------------
Microsoft Visual FoxPro
---------------------------
Error #:     230
Message:     Array dimensions are invalid.
Code:        Thisform.cVersionControlClass   = This.aItems[This.ListIndex, 2]
Line #:      1
Method:      projectexplorersolutionproperties.cboVersionControl.anychange

Choose Yes to display the debugger, No to continue without the debugger, or Cancel to cancel execution
---------------------------
Yes   No   Cancel   
---------------------------

**Comment by DougHennig** [comment]
Does ProjectExplorerSettings.xml exist in the Project Explorer folder?

**Comment by paulmrozowski** [comment]
Yes. The latest update seemed to resolve this.
