### ISSUE TITLE
Add MRU class list to New Class dialog

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#43]
At minimum, it would be nice if the "Based on" name in the New Class dialog defaulted to the class that was used the last time a class was created. Better yet would be if the last X classes that were subclassed would be included in the list of classes in the "Based on" dropdown list. Maybe all those classes would appear at the top of the list, followed by a separator line then all the VFP base classes.

**Comment by DougHennig** [comment]
The default is now the selected class as per #44.

I've added an MRU list of VCXs for the "From" control. This isn't exactly the same as you've requested but might be just as convenient because the Based On list comes from the selected VCX, which makes it more complicated to have an MRU list of classes.. Let me know what you think once you try the new release.

**Comment by mikepotjer** [comment]
I think your solution for this is better than what I suggested. I did run into a bug when testing it, though. My “From” list didn’t have anything in it, so I tried selecting the ellipsis button next to it to see what would happen once I had some items in the list. Unfortunately I got the error below. Hopefully these screenshots cover everything, but let me know if you need any more information.

![image](https://user-images.githubusercontent.com/9847353/32303056-8efc5f6c-bf3c-11e7-8d51-13d1e256336c.png)

![image](https://user-images.githubusercontent.com/9847353/32303058-9485b7ee-bf3c-11e7-8d1e-cfeb4551ed1b.png)

![image](https://user-images.githubusercontent.com/9847353/32303070-9a402868-bf3c-11e7-87d5-898896adc474.png)



Thanks,
Mike Potjer

**Comment by DougHennig** [comment]
Fixed in the latest release.

**Comment by mikepotjer** [comment]
I didn't test this extensively, but it is working for me now.
