### ISSUE TITLE
Add a New Class option to item shortcut menu

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#45]
When a class or class library is selected in the Project Explorer, it would be handy if the pop-up shortcut menu for that item would include a New Class option. The developer is often selecting the class library that the class is going to be added to, so the shortcut item reduces the number of clicks and mouse movements needed for this task.

**Comment by DougHennig** [comment]
I'm not sure this is needed anymore since the New button for a class (which is a single mouse click) fills in defaults for everything but the class name now.

**Comment by mikepotjer** [comment]
I was kind of spit-balling ideas, so this isn't a big deal. It would be a **little** more convenient to be able to simply right-click the class or class library, and select New Class from the shortcut menu, but probably not worth the trouble. This would still be 2 clicks, so it's only the mouse movement between clicks that would be shorter.

**Comment by DougHennig** [comment]
This could be handled with an add-in: adding an item to the shortcut menu that calls the NewItem method of the form.

**Comment by mikepotjer** [comment]
Sounds good. If I end up creating an add-in for this, I'll be sure to send it to you (probably as a pull request).
