### ISSUE TITLE
Add option to create a duplicate class

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#46]
In the Finder tool available through Thor, when a class is selected in the list, it includes an option in its shortcut menu to create a duplicate class. There have been many times when it was quicker for me to copy and edit an existing class, rather than create a new one from scratch, and there wasn't an advantage to creating a new class to serve as the parent for both classes. In Finder, there is a separate shortcut menu item and a custom dialog just for creating duplicate classes. However, if a checkbox were added to the New Class dialog, this feature could be implemented without adding any new buttons or menu items to the Project Explorer. The checkbox would probably be directly below the "Based on" list, and could have a label such as "Create a copy of this class". The checkbox would not be checked by default.

**Comment by DougHennig** [comment]
I added this in the latest release.
