### ISSUE TITLE
Add a Sort/Filter indicator to the tool bar

### ISSUE THREAD

**Issue by mikepotjer** [DougHennig/ProjectExplorer#47]
Add a button or image to the Project Explorer tool bar to indicate that the project items are being sorted and/or filtered. The tool tip for this item could display the current sort and filter settings. If this were a button with a dropdown menu, it could include an option to clear/reset the filter as mention in item #42, and an option to open the Sort/Filter dialog. There could be another menu item to toggle the sort order between ascending and descending, so you wouldn't need to open the dialog if that's all you wanted to change.

**Comment by DougHennig** [comment]
I replaced the Refresh button with a Sort/Filter button. Clicking it invokes the Sort & Filter dialog and its tooltip shows the current sort/filter if it isn't the defaults. Right-clicking the button resets the sort and filter.

**Comment by mikepotjer** [comment]
I did some testing with this, and it is working fine for me.
