### ISSUE TITLE
DVCS Assumption

### ISSUE THREAD

**Issue by RGBean** [DougHennig/ProjectExplorer#49]
The configuration assumes you will pick either GIT or Mercurial, and fails when trying to add a new tag if neither is picked. The check in the class method projectexplorerui.projectexplorerform.assigntags() assumes loVersionControl.lAutoCommitChanges is an object. I fixed this assumption by adding "VARTYPE(loVersionControl) = 'O' AND " in front of the two cases where the object assumption was made. I'm sure there are other ways to fix this, but it was good enough for me right now.

**Comment by DougHennig** [comment]
Fixed in the new release.
