### ISSUE TITLE
Support other version control providers

### ISSUE THREAD

**Issue by DougHennig** [DougHennig/ProjectExplorer#51]
Version control providers that integrate with VFP, such as SourceSafe and SourceGear Vault, aren’t currently supported. Add support for the associated properties: SCCProvider for the project and SCCStatus for files, plus add methods to shortcut menu that call item methods: AddToSCC, CheckIn, CheckOut, GetLatestVersion, RemoveFromSCC, and UndoCheckOut.

**Comment by oiBio** [comment]
SourceSafe integration would be really great!

**Comment by DougHennig** [comment]
Since I don't have SourceSafe, I have no way to test it. So, while I'll add support for those properties at some point, someone else will have to write the integration code.
