### ISSUE TITLE
Add a 'Classes' parent node to the TreeView

### ISSUE THREAD

**Issue by RickBorup** [DougHennig/ProjectExplorer#53]
Suggestion: Add a 'Classes' parent node to the TreeView, at the same level as 'Forms', 'Reports', etc., and place all visual class libraries under it.

**Comment by DougHennig** [comment]
This is only needed when All is chosen, correct?

**Comment by RickBorup** [comment]
_>This is only needed when All is chosen, correct?_

I envisioned it being like the other 2nd level nodes (Code, Data, Documents, and Other), but I can see where that might be redundant and could be problematic given how 'All' is implemented differently (and better) in Project Explorer than in the VFP Project Manager. 

For example, in Project Explorer, when Code is chosen, the TreeView hierarchy is

  ProjectName
  |_Programs
&nbsp;&nbsp;&nbsp;&nbsp;|_list of programs
  |_API Libraries
  |_Applications

and when Documents is chosen the TreeView hierarchy is

  ProjectName
  |_Forms
&nbsp;&nbsp;&nbsp;&nbsp;|_list of forms
  |_Reports
  |_Labels

The idea is that when Classes is chosen, the TreeView hierarchy would be

  ProjectName
  |_Classes [or Class Libraries]
&nbsp;&nbsp;&nbsp;&nbsp;|_list of class libraries

When All is chosen, the Classes node would exist at the same level as the rest and could be expanded to show the individual class libraries.

  ProjectName
  |_Forms
  |_Reports
  |_Labels
  |_Databases
  |_Free Tables
  |_Queries
  |_Programs
  |_API Libraries
  |_Applications
  |_Menus
  |_Text Files
  |_Other Files
  |_Classes [or Class Libraries]

**Comment by DougHennig** [comment]
I think I'll skip the heading node when Classes is chosen because it's one more level and doesn't add anything. However, it's definitely needed when All or any custom tag that has classes is chosen.

**Comment by RickBorup** [comment]
Sounds good.

**Comment by DougHennig** [comment]
Added in the latest release.
