### ISSUE TITLE
User editbox zoom

### ISSUE THREAD

**Issue by rschummer** [DougHennig/ProjectExplorer#57]
Enhancement request: User editbox to zoom to larger window two ways.

Anchor the edit box so it expands when resizing the Project Explorer.

Hyperlink the User label to open new form with larger editbox on resizable form that allows me to make it even larger.

**Comment by DougHennig** [comment]
Done in the latest build: right-click the editbox and choose Zoom. Didn't change anchoring of the editbox due to other controls.

**Comment by rschummer** [comment]
Works great. Thanks.
