### ISSUE TITLE
Project Builder feature missing

### ISSUE THREAD

**Issue by rschummer** [DougHennig/ProjectExplorer#58]
Based on my fancy with builders and the fact I have a Project Builder, I noticed that the right-click on the Project Explorer is missing the menu option. It can be added by executing the following code.

DO (_wizard) WITH "Project"

It does the exact same thing as behavior with the Project Manager, which is to bring up the dialog to select the builder. Logically deleting or renaming the Type in the Wizard.DBF for Application Builder and Web Services Builder helps automatically run your one project builder you probably want to use. Otherwise you get the prompt each time.  

Yes, it is not intuitive to run the Wizards.APP and pass it the parameter when this is a builder.  Looking at the Builder.APP makes it easier to understand why this approach was taken.

I am not sure if this is better as an add-on or part of the base tool. If an add-on is better let me know and I will put one together. Thanks for consideration.

**Comment by DougHennig** [comment]
I added it to the base tool. It'll be in the next release.
