### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#59]
Hello Doug,
thanks for your great tool :-)

I whish to set the font-size in Project-Explorer to 12 or 14 because i have high-resolution monitors.
For me it is no option to increase windows-dpi.

-- 
Hans-Peter Grözinger

**Comment by HaPe4** [comment]
Suggestion for an easy to implement font-sizer:
- Add nFontSize = 9 to project explorer form
- Add the following code to the MOUSEWHEEL-EVENT for example the toolbar:
```
LPARAMETERS nDirection AS INTEGER, nShift AS INTEGER, nXCoord AS INTEGER, nYCoord AS INTEGER

LOCAL llReturn AS BOOLEAN

*-- Ctrl-key pressed
IF nShift = 2

	*-- Increase font-size
	IF nDirection > 0
		IF THISFORM.nFontSize < 14
			THISFORM.nFontSize = THISFORM.nFontSize + 1
		ENDIF

	*-- Decrease font-size
	ELSE
		IF THISFORM.nFontSize > 8
			THISFORM.nFontSize = THISFORM.nFontSize - 1
		ENDIF
	ENDIF

	*-- Set font-size
	THISFORM.SETALL( 'FONTSIZE', THISFORM.nFontSize )

	*-- Set font-size in TreeView
	THISFORM.oTreeViewContainer.oTree.FONT.SIZE = THISFORM.nFontSize
ENDIF

llReturn = DODEFAULT( nDirection, nShift, nXCoord, nYCoord )

RETURN( llReturn )
```

By pressing the ctrl-key when mouse-pointer is over the toolbar and 'wheeling' the mouse, font-size increase or decrease :-)
Save THISFORM.nFontSize with position of the Project Explorer.

For optimization:
- use SetFontSize( THISFORM.nFontSize ) instead of THISFORM.SETALL( 'FONTSIZE', THISFORM.nFontSize ) and THISFORM.oTreeViewContainer.oTree.FONT.SIZE = THISFORM.nFontSize
SetFontSize:
```
LPARAMETERS tnFontSize AS INTEGER

LOCAL lnFontSize AS INTEGER, lnMargin AS INTEGER

*-- Check parameter
IF VARTYPE( tnFontSize ) == 'N'
	lnFontSize = tnFontSize
	THIS.nFontSize = lnFontSize
ELSE
	lnFontSize = THIS.nFontSize
ENDIF

*-- Set margin-size for textboxes, spinners, etc.
DO CASE
	CASE lnFontSize < 9
		lnMargin = 2
	CASE lnFontSize = 9
		lnMargin = 2
	CASE lnFontSize = 10
		lnMargin = 1
	CASE lnFontSize = 11
		lnMargin = 1
	CASE lnFontSize = 12
		lnMargin = 0
	OTHERWISE
		lnMargin = 0
ENDCASE

*-- Set font-size and margin
THIS.SETALL( 'FONTSIZE', lnFontSize )
THISFORM.oTreeViewContainer.oTree.FONT.SIZE = lnFontSize
THIS.SETALL( 'MARGIN', lnMargin )

```

**Comment by DougHennig** [comment]
The problem I see is the control spacing for the properties. Increasing the font size will make all the controls bigger and therefore closer together, possibly even overlapping.

**Comment by HaPe4** [comment]
It works for me (in my applications) with a font-size from 8 to 14 pixel.
I use a horizontal TOP-difference of 27 and (left-)anchor all controls.
When MARGIN is set to 0 on a font-size of 12 and higher it is OK for me.

> possibly even overlapping.

In this case the WIDTH of a form has to be increased by the user.

See the video:
http://www.schwaben-team.de/downloads/dfpug/fontsizer/fontsizer.wmv

**Comment by DougHennig** [comment]
Here's what happens when I changed to the font to 12 using this code:

```
x = _screen.oprojectexplorers(1)
x.SetAll('FontSize', 12)
x.oTreeViewContainer.oTree.Font.Size = 12
```

![font](https://user-images.githubusercontent.com/12052409/33224710-00ea362e-d132-11e7-8adc-0d054fc897d6.png)

Notice the overlapping controls at the right. 

Rather than building this functionality in, you can do it with an add-in using the following code:

```
* This addin sets the font when the Project Explorer is started.

lparameters toParameter1, ;
	tuParameter2, ;
	tuParameter3

* If this is a registration call, tell the addin manager which method we're
* an addin for.

if pcount() = 1
	toParameter1.Method = 'OnStartup'
	toParameter1.Active = .T.
	return
endif

* Refresh registered addins.

toParameter1.SetAll('FontSize', 12)
toParameter1.oTreeViewContainer.oTree.Font.Size = 12
```

**Comment by HaPe4** [comment]
> Notice the overlapping controls at the right.

Yes, an overlapping will occur.

If set the ANCHOR value of the controls (TextBox, ComboBox, etc.) to left relative and not to left absolute it works when user increases the property-container or the form or drag the splitter.
![fontsizer2](https://user-images.githubusercontent.com/29651009/33229294-8abc9668-d1cc-11e7-9f4a-1fa52ddb4462.jpg)

Anyway, I will give the font-sizer-addin a try :-)

**Comment by HaPe4** [comment]
> Anyway, I will give the font-sizer-addin a try :-)

Hmm, I try but the result don'nt satisfy me :-(
With font 11 it looks not good.
Not because by the overlapping of the labels and input-controls, the visual-problem is the overlapping of the input-controls itselfs.

![fontsizer3](https://user-images.githubusercontent.com/29651009/33229664-42f39334-d1d3-11e7-82eb-99ef8049ac79.jpg)

Why increase your "baseclases" the control-height when font is sizing up?
It is better to minimize the MARGIN-value of an input-control when font-size grows.

Please take a look to my screenshots again. I think this way is much better and looks nearly good with bigger font-size.

**Comment by DougHennig** [comment]
Thanks for the suggestions. Try the latest release and see how it works for you. You will need to move the splitter to adjust the control properly.

By the way, I am on vacation for the next week so I won't be responding until I get back on December 4.

**Comment by HaPe4** [comment]
Thanks Doug :-)
Now it works great for me.
Have a nice vacation.
