### ISSUE TITLE
Reduce panel size on right pane.

### ISSUE THREAD

**Issue by mattslay** [DougHennig/ProjectExplorer#6]
I find the large pane on the right side of PE to be way to excessive use of my screen space, for what little bit of data is actually shows me.  
![2017-05-24_17-28-54](https://cloud.githubusercontent.com/assets/309016/26428444/590a9022-40a7-11e7-8f61-6ad9428333a9.png)

**Comment by DougHennig** [comment]
You can collapse the pane by clicking the Collapse/Expand button in the toolbar (the third one from the right).

**Comment by mattslay** [comment]
Oops, missed that icon!!  

Nice.
