### ISSUE TITLE
Save and restore Project Explorer position

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#60]
Is it possible to save Project Explorer position and restore when Project Explorer is opened next time?
In version 1.0.6533 i see no position-restore of the Project Explorer window.
I use 4 monitors with 1920x1080 resolution and the Project Explorer window ist set to dockable in the Options-window.

-- 
Hans-Peter Grözinger

**Comment by DougHennig** [comment]
Thanks for the details, especially mentioning that dockable was turned on. That was the key: it was restoring the size and position except in that case, Fixed in the latest release.
