### ISSUE TITLE
Operator/operand type mismatch (Error 107)

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#61]
When Project Explorer ist open and i do a CLEAR ALL the following error occur:
Operator/operand type mismatch (Error 107)

I need this for compiling PRGs, VCXs and SCXs before zipping to archive a project.

-- 
Hans-Peter Grözinger

**Comment by DougHennig** [comment]
Since Project Explorer is a VFP app, you can't use CLEAR ALL while it's open. You have to close it, then use CLEAR ALL, then reopen it.
