### ISSUE TITLE
Error building key for Index

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#62]
Opend first project, selcted "All" in Toolbar combobox:
Error message, short:

---------------------------
Project Explorer
---------------------------
The sort (str(ORDER, 7) + strtran(upper(TEXT), chr(216) + ' ')) is invalid. The error message is:
Error building key for index "c:\users\lutz\appdata\local\temp\00008dft004u.cdx" tag "Sort".

**Comment by DougHennig** [comment]
I do not get this error message but can see where it might occur. Let me know if you still see this in the latest release.

**Comment by lscheffler** [comment]
Hm, I can't reproduce with commit f7bc460ed3f533fab9, but I didn't know what the old commit was. It was the very first run.
