### ISSUE TITLE
ToolTipText of cmdNew Button

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#63]
The ToolTiptext of the cmdNew stucks to _Create a new file and add it to the project_ even if inside a vcx on the tree. It should be _Create a new class in the lib selected_ or the like.
I guess it could be similar for tables and the like, but I do not use this.

**Comment by DougHennig** [comment]
Fixed in the latest release.

**Comment by lscheffler** [comment]
Works! Thanks!
