### ISSUE TITLE
cmdAdd and ClassLibs

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#64]
Entering a non existing name of a vcx does not create the vcx. (Same as on build in manager)
Better would be to test FILE() and run CREATE CLASSLIB
Edit:
Note that there is no new available for classlibs, because on the classlib node add goes for classes.

**Comment by DougHennig** [comment]
Rather than adding a file and typing the name of a non-existent VCX, click New and specify the name of the non-existent VCX in the Store In setting. That creates the VCX and puts the new class into it.

**Comment by lscheffler** [comment]
Ok, something new learned. (I never came to this idea. I issued CREAT CLASSLIB on the command line all the time ...)

I like empty vcx's. :)
