### ISSUE TITLE
Adding / opening a pjx that is open in the same instance of VFP

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#65]
This raises a system error (it's german so I guess it's a system error) that the pjx is open in a different program. No other program is involved
Expected behaviour would be to ask me if I like to close the pjx, or quitly close and reopen the pjx :)

**Comment by DougHennig** [comment]
I am not seeing that. I did this in a folder where I had previously created a solution:

MODIFY PROJECT DEMO1
do ProjectExplorer.app

I see both the Project Manager and Project Explorer open.

Maybe it's an environment thing, such as some SET setting you have that's different than mine.

**Comment by lscheffler** [comment]
Yeah, the project explorer opens empty, asking me for an XML, I choose Demo1.pjx instead.

I can forward you a screenshot to your email, if you like.

**Comment by DougHennig** [comment]
OK, I can reproduce it with those steps when there is no Solution.xml in the folder. I'll fix that.

**Comment by lscheffler** [comment]
What I see is, that you run OPEN dialog outside the IDE, at least the Windows start menu shows an VFP Icon labled "Open"

**Comment by lscheffler** [comment]
Ok, I see this over and over, because the current path never contains the solution.xml. You create it next to the pjx. That's fine, but I would need to use the filepath as parameter. (IOW my SET DEFAULT is not the place where I store my pjx)

**Comment by lscheffler** [comment]
Do you have an event for AfterStart that is before openening the solution so that I can insert my path via AddIn

**Comment by DougHennig** [comment]
OK, fixed in the latest release. Now, with a project open in the Project Manager, opening Project Explorer and selecting that project now opens it in Project Explorer without an error.

You can pass a path to Project Explorer with DO ProjectExplorer.APP WITH file, where file is the path to a PJX or Solution.xml file.

**Comment by lscheffler** [comment]
O.k. this works.

Yes I know I can hand a parameter to the app

**Comment by lscheffler** [comment]
Not closed,

The first project works now, but I'm unable to included a second pjx.
Same error

**Comment by DougHennig** [comment]
What do you mean by including a second PJX? Do you mean that you are adding a project to the solution and getting an error? Is that PJX already open in the Project Manager? Steps to reproduce would be helpful.

**Comment by lscheffler** [comment]
I have added a second pjx. This pjx was open in the IDE as well.
May current path is not the path where the pjx is located.

**Comment by DougHennig** [comment]
Fixed in the latest release.
