### ISSUE TITLE
Filetypes for cmdAdd

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#67]
The filetype available for add depends on the node one is on.
It could be all files available for new, and the file could be sorted later. Same for add. The best guess on top of the list.
Also new for classlibs, even if it is available from project node only. See issue #64

**Comment by DougHennig** [comment]
If I understand what you're saying, you would like the New and Add buttons to allow you to choose any file type rather than just the type that matches the node you are currently on. Is that correct?

**Comment by lscheffler** [comment]
Yess, that's what I mean.

**Comment by DougHennig** [comment]
I have this working for the Add button but there's an issue with the New button: since a class isn't a file, how would you indicate that you want a new class if it opens a dialog asking for a file?

**Comment by lscheffler** [comment]
For the _New_ dialoge if inside an ClassLib. It should create a class like on ProjectManager, and not asking for anything else then an vcx. This one is special, and one would require an extra buttom - a waste of space. I would not touch the behaviour to create a vcx on the fly there too.
For any other place where new means file. Same as add. 
Since you have no classlib node, the classlibs parent, IOW the pjx node, should have vcx topmost.

**Comment by DougHennig** [comment]
This has been implemented in the latest release. To enable it, choose Options from the menu and turn on Add and New Allow All File Types.

**Comment by lscheffler** [comment]
Would be nice to have vcx's on the list. As Default for Project node.

Also _new_ on Project node returns messagebox:

---------------------------
The selected type could not be determined.
---------------------------

It had worked once, then I've rerun to ProjectExplorer

**Comment by DougHennig** [comment]
Both of these are resolved in the latest release.

**Comment by lscheffler** [comment]
Now VCX As Default for Project node.

Please. ;)

**Comment by DougHennig** [comment]
The problem is that someone else might want a different default, such as PRG. You can select the type you want from the combobox in the File dialog.

**Comment by lscheffler** [comment]
But prg should be the default for  _Programs_ node.
Lock what I mean:
New file / add file holds all files in the combobox
Now
active node / default
Programs / prg
menu / mnx
reports / frx
forms / scx
..

Anything covered? Basically yes. Except:
There is no _class library_ as parent for  classlibs where vcx would be default.
The only parent for classlibs is _The project_
There is just a random default on project or vcx because it's it.
Just fix issue #64, and this will be gone. I think you should focus on #64 it solves both.

**Comment by DougHennig** [comment]
#64 is fixed now: choosing VCX as the type of file creates an empty VCX. The latest release now defaults to VCX when a project is selected for the Classes tag.

**Comment by lscheffler** [comment]
ups, I meant #53 .... But yes this works pretty well
