### ISSUE TITLE
Change Value of cboTagFilter

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#69]
If the cboTagFilter is changed to "All", it should try to focus the last node, or see below.
Possibly focus active node fitting to value of the combobox.
Keep expanded nodes expanded, fitting to value of combobox.
Store expanded state of nodes, even over apps shutdown. (as the projectmanager does)

This is important to mimic behavior to overcome issues with CLEAR ALL that would require to reopen Project Explorer. It's no problem to close the ProjectExplorer and recall it later, but it should reopen to the same state.

**Comment by DougHennig** [comment]
It does currently restore the state of which tag you selected in the combobox, which nodes were expanded, and which node was selected when you reopen Project Explorer, except if you select "All". I will fix it so it works for All as well.

**Comment by DougHennig** [comment]
Fixed in the latest release.
