### ISSUE TITLE
Closing projects on closing ProjectExplorer

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#71]
I understand that the ProjectExplorer uses VFP projectmanager. It opens and close them in the background.

Now there is a small hickup if the projectmanager is visible. Possibly the project was open from the start, or it's opened it with _modify project_, what will make the project loaded with noshow visible. 
Closing ProjectExplorer closes projectmanager. It should not happen if _projectmanager.visible_ is true.

**Comment by DougHennig** [comment]
This is done in the next release (not pushed yet; waiting for your answer to my question for #67).
