### ISSUE TITLE
General github

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#74]
How about opening the label or the Team discussions function of github?

**Comment by DougHennig** [comment]
I'm new to GitHub. How do I do that?

**Comment by lscheffler** [comment]
There is a button above the issues table named _Label_. There is same more information about labels. One can mark issues with a information docu or the like. You can set it. I guess I'm not, because I would need to have write access. (As far as I understand)

Team discussion would require some team building. There is something about it on the github homepage.

**Comment by DougHennig** [comment]
As far as I can tell, you can label an issue when you create it.

I added you as a collaborator on the project.

**Comment by lscheffler** [comment]
I have reentered github, but stillse no way to set it. I will head forward with the issues from the Frankfurt conference first. :)

**Comment by lscheffler** [comment]
I have accepted you invitation and now the labels are changable on the list and I can set them creating a new one.
