### ISSUE TITLE
Addins Execution , Question

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#75]
Your template for addins gives some uses for return codes. It states for .f.,0,1 the execution of addins should be stopped.
I see not how the execution is stopped (Method _ExecuteAddin_).
If I have more then one addin with the same method, your scan will run through all those addins. If one returns .f./0 it sets some text and _lSuccess_ property. If the return is 1 the text is set. But the next addin will run anyway.

What means _to not continue_?

Edit:
Ah! This more for the BEFORE* stuff to stop execution.
Well, on multiple addins this is tricky. Looks like you need a additional return to stop it at all ....

Needs a second thought

**Comment by DougHennig** [comment]
It isn't the execution of addins that stops, it's the method that calls them. For example, ProjectOperations.BuildProject calls ProjectAddins.ExecuteAddin with "BeforeBuildProject" as the addin method. If there is more than one BeforeBuildProject addin, they all have an opportunity to execute (that is, one of them returning 1 or .F. doesn't prevent the others from executing), but if any of them returns 1 or .F., BuildProject stops and doesn't build the project.

**Comment by lscheffler** [comment]
I can understand, but still feel funny. This has many sides.
