### ISSUE TITLE
Run for classes

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#78]
Run for classes is disabled. On the other side one can instaniate a class by dropping into _SCREEN.

Wouldn't _run_ mean instantiate to _SCREEN ?

**Comment by DougHennig** [comment]
Where should it put the object: at 0, 0? If so, then running more than one class would put them on top of each other and it would get messy.

**Comment by lscheffler** [comment]
:)
This is a problem.

Yes 0,0. And if the developer decides in his wisdom to run a second one ...

Possibly instantiate an empty form and hook the class to it? [gdr]

This minor.

**Comment by DougHennig** [comment]
Implemented in the next release.
