### ISSUE TITLE
Get FoxBin2PRG settings

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#81]
FoxBin2Prg may have settings file in each individual directory.
They should be respected.
The best way to get them, is FoxBin2Prg itself.

I can assist how to do this.

**Comment by DougHennig** [comment]
When FoxBin2PRG is called, does it not automatically use the CFG file in the project's folder to override the global settings?

**Comment by lscheffler** [comment]
Yes. But.

It may have settings (config files) in each subfolder too. It will respect those as well. :)
I do not favor the idea, but people may do something the like. And you might create havoc when you process the wrong files.
For all I understand you commit single files, so you need to be carfull with the file naming.

I do simple 
```
do FoxBin2Prg ...
git add .
git commit
```
so I do not need to care about

If you instantiate FoxBin2PRG as an object, there is a method `Get_DirSettings(m.tcDir)` that will return an object with all info per directory.

**Comment by DougHennig** [comment]
This is handled in the latest release.
