### ISSUE TITLE
Drag 'n' Drop between ClassLibs

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#83]
There is an issue with VFP's way to copy projects by _ADD CLASS_ This was always been true.

The problem is to be respected in issue #46.

If you copy a class via _ADD CLASS_, all the records representing a class will be appended to the target vcx. It might change the timestamp and it will adjust paths.
The thing that will not be touched is the UniqueID.
A lot of people copy to a second vcx, rename, and copy back to create a similar class.
Now we have two classes with a not so unique UniqueID field. there is no problem with that - except the CodeReference. This offers a ability to REPLACE code snippets. And this relays on UniqueID. As you can guess, this will create havoc.
So the REPLACE function is known for destroying VCX's for this. 

So one need to change the UniqueID field after ADD CLASS on the target. So for Drag'N'Drop classes you could raise a AddIn so I can add this. As long as I know class name and target file.

**Comment by DougHennig** [comment]
Implemented in the latest release.
