### ISSUE TITLE
FoxBin2Text file extensions

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#84]
The file extensions of FoxBin2Text are defined in config files. They should be respected for creating and rebuilding. See issue #81 how to get them.

**Comment by DougHennig** [comment]
Note to myself: this affects GetBinaryFileName.prg and GetTextFileName.prg.

**Comment by DougHennig** [comment]
It looks like I have to instantiate c_foxbin2prg in FoxBin2PRG.prg and check the c_VC2, c_SC2, etc. properties. Is that correct?

**Comment by lscheffler** [comment]
Exactly. See my comment to issue #81.

**Comment by DougHennig** [comment]
This is handled in the latest release.
