### ISSUE TITLE
Closing pjx on closing ProjectExplorer (Again)

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#87]
Following issue #71 
The ProjectManager will stay open if it was open on ProjectExplorers start. That's fine.

If I issue MODI PROJ *after* ProjectExplorer start, the ProjectManager becomes visible. But it is closing when ProjectExplorers closes. You should check ProjectManager VISIBLE property on closing. This is most meaningfull.

**Comment by DougHennig** [comment]
Fixed in the latest release.
