### ISSUE TITLE
Source control per solution

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#88]
This is something I'm not sure if it will fit everybody.

There is a switch _Solution uses version control_
I havo no idea of Mercurial, but for git this means that the folder and the subfolders where the xml is placed is gitted. 

But this does not mean that a pjx and its subfolder are under git control, because they can be located under a complete different path. 

*I* place my solution.xml in the git root folder where the projects are located too, so it's perfectly fine to me. Also the project files are all in subdirectories of this.
But there is nothing on VFP and on ProjectExplorer enforcing this.

I can figure out of a directory is under git control, but we need to make it clear to the user that is unwise to open a pjx / files outside directory structure given by the XML file.

It would be very easy to have solution with mixed gited / ungited projects.

**Comment by DougHennig** [comment]
Project Explorer automatically puts Solution.xml in the same folder as the PJX you open with Project Explorer, so unless you move the file manually, it isn't possible for the solution file to be in a different folder. However, it is currently possible to add a second project that is in a different folder (not a subdirectory of the solution folder) (issue #89) so I will fix that to prevent it.

Project Explorer does support some items being under source control and other not in the same solution.

**Comment by lscheffler** [comment]
Basically that's the idea.

For stuff under source control or not in one solution, see issue #91 for my opinion.

I don't care, as long as I can enforce it for me. :)

**Comment by DougHennig** [comment]
Please close this if issue 91 works as you expect.
