### ISSUE TITLE
Mixed projects paths

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#89]
I can create a solution like (issue #88 ).

D:\x\Proj\solution.xml
with
D:\x\Proj\Demo1.pjx
and
D:\x\Somewhereelse\Demo2.pjx

but I can not reopen.
I get 
D:\x\Proj\Demo2.pjx not found.

No problem, to clean up the xml, but it should either
clean it up itself, at least after prompting the user
or
store the correct path.

Or (issue #88) do not let ProjectExplorer add the pjx at all.

**Comment by DougHennig** [comment]
The latest release gives a warning message if you add a project to the solution that isn't in the folder structure (that is, the same folder as the solution or a subdirectory).
