### ISSUE TITLE
Tags - How to do some hacking?

### ISSUE THREAD

**Issue by mattslay** [DougHennig/ProjectExplorer#9]
I've added the tags (per your instructions in Issue # 7), and I made a few manual updates through the UI. However, I'd like to hack one of the tables somewhere to do mass-updates to change the Tag for all SCX files to "Forms" and all FRX files to "Reports".

I see a dbf named "Blah_MetaData.dbf" and I see a Key column there and the Tags memo field. So, where I can resolve what filename the Key points to? With that info, I can do the hack that I want to do.

**Comment by DougHennig** [comment]
I updated ProjectExplorer.pdf to describe how IDs are created for items. That being said, Paul created an issue to do a bulk update of tags for item so I'm looking into that.

**Comment by DougHennig** [comment]
In the latest commit, choose Assign Tags for Items from the File menu to specify the tags to add and the filter condition for the items.
