### ISSUE TITLE
Adding source control

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#90]
If you put a solution under version control, an addin should be called to figure out if the solution is under already under source control and return root folder. 
If found no further action is required.
See issue #91

**Comment by DougHennig** [comment]
Done in the latest release.

**Comment by lscheffler** [comment]
what addin, parameters, and where to store to information to. please :)

**Comment by DougHennig** [comment]
No addin needed; the core code does it.

**Comment by lscheffler** [comment]
Works.

**Comment by lscheffler** [comment]
Well, as far as I read issue #91, you look for _Solutionfolder/.git_ folder with VFP commands.
for git there is a better solution
**use git**

From my [Bin2Text](https://github.com/lscheffler/bin2text) project, runb2t.prg

```
FUNCTION Is_git		&&Internal. Check if a directory is under git control
 LPARAMETERS;
  tcPath

 LOCAL;
  llIs_git AS BOOLEAN

 llIs_git = !EMPTY(GetGitBaseDir(tcPath))
 
 RETURN llIs_git
ENDFUNC &&Is_Git


FUNCTION GetGitBaseDir		&&Internal. Return git root directory
 LPARAMETERS;
  tcPath


 LOCAL;
  lcTemp   AS CHARACTER,;
  lc_Git   AS CHARACTER,;
  lcReturn AS CHARACTER

 lcReturn = ''

 IF VARTYPE(tcPath)#'C' THEN
  tcPath = FULLPATH(CURDIR())
 ENDIF &&VARTYPE(tcPath)#'C'


 IF Get_git_Path(@lc_Git) THEN

  lcTemp = FORCEPATH('git_x.tmp',tcPath)

  IF Run_ExtApp('cmd /c "'+lc_Git+'" rev-parse --show-toplevel>>git_x.tmp',tcPath,'HID') THEN
   IF FILE(lcTemp) THEN
    lcReturn = CHRTRAN(FILETOSTR(lcTemp),'/'+0h0d0a,'\')
   ENDIF &&FILE(lcTemp)
  ENDIF &&Run_ExtApp('cmd /c "'+lc_Git+'" rev-parse --show-toplevel>>git_x.tmp',tcPath,'HID')

  DELETE FILE &lcTemp

 ENDIF &&Get_git_Path(@lc_git)

 RETURN lcReturn
ENDFUNC &&GetGitBaseDir
```

Note: If you issue the git command on command line, the output you see on an ungited folder goes to StdErr and is not visible to the file above.

---------------

_Get_git_Path_ returns the location of git on the comp, 
_Run_ExtApp_ is a wrapper for Ed Raus API_AppRun

**Comment by DougHennig** [comment]
Implemented in the latest release. Thanks for the code.

**Comment by lscheffler** [comment]
My first idea was to put this to an addin, so other source control providers could be added too.
Bin2Text also holds code to return current branch (what I consider nice to caption)

**Comment by DougHennig** [comment]
There are subclasses for each type of source control provider so someone could add Subversion and implement the Subversion version of this code in the subclass.
