### ISSUE TITLE
Placing a solution under source control

### ISSUE THREAD

**Issue by lscheffler** [DougHennig/ProjectExplorer#91]
If a solution is placed under source control that is already undere source control (issue #90) you ask for repository folder.

Under git this would be the .git folder. Normaly this is a invisible folder.

Do you mean the root folder? The _root_ under that anything is under source control?

**Comment by DougHennig** [comment]
What it is asking for is the parent folder of the .git or .hg folder.

**Comment by lscheffler** [comment]
That's what I understand.
But the word _repository_ means .git folder under git. What you mean is more _(project)root_.
Git documentation refers to it as _project’s directory_

I only did not pick the .git folder because I thought this to sophisticated... :)
AFAIK, the .git folder must not be within the root folder, but I guess you will not mean such a scenario. So I was a bit puzzled.

**Comment by DougHennig** [comment]
I changed the message in the dialog to "Select the parent folder of the repository folder" to make it clear it needs the folder containing the .git or .hg folder.

The reason it asks for this is because it doesn't assume the folder containing the PJX file also contains the .git/.hg folder so it asks for the location.

**Comment by lscheffler** [comment]
I understand the reason (in general).

The problem is that we both have a higher level in understanding source control then the common VFP developer. Probably he will not understand repository and .git or .hg folder might be hidden.
I understand what you mean with your messagebox, but argh it's tricky.

My way of doing this is just anything starting from root folder is under git source control, and this is controled by .gitignore only.
*git add .* and go style.

Controling single bits of projects (except the bin/text problem of VFP) is VSS, not git style. In this sense commiting single files is akward. A git commit should hold a complete snapshot. This is complete strange from the VSS viewpoint, but works.

git add filename
Is more something to solve conflicts or patching stuff.

My idea of autocommiting (issue #80 ) would commit every file change, single files, but because this is the snapshot of this very moment.

Issue #91 could fix the root folder search anyway, it can return the project root :)

**Comment by DougHennig** [comment]
I personally have a repository where it is at a higher level than the project because the repository contains several applications (unusual I know, but it's the way we implemented version control at the time). So, the design of Project Explorer can handle this case as well as the more usual case where the .git folder in either in the same folder as the PJX or a parent folder. Asking the user to locate it makes the most sense to handle these different cases.

**Comment by DougHennig** [comment]
As per issue 90, it now detects if a .git or .hg folder exists in the solution folder and if so, doesn't ask the user to create or locate the repository.

**Comment by lscheffler** [comment]
I give you an example

If you do
D:\X\MyRoot
D:\X\MyRoot\.git
D:\X\MyRoot\Y\Demo1.pjx
D:\X\MyRoot\Z\Demo2.pjx
D:\X\MyRoot\solution.xml

This is perfectly well.

Anyway, all I need is some point to hook into this. If you set source control on / git and it is gited and git is installed (issue #73 ), I can return _D:\X\MyRoot_ if you point to Demo1 or Demo2 ore somewhere else as long as it starts with _D:\X\MyRoot_ (issue #90) I retrieve this from git directly.
If activate source control for _D:\X\MyRoot\solution.xml_  and give me the path anything is fine.
If I retrieve it, you can stop asking the user, and if I found nothing you may ask if he like to git init. Because if there is nothing I found ther is nothing to point to.

If you mean

D:\X\MyRoot
D:\X\MyRoot\Y\Demo1.pjx
D:\X\MyRoot\Y\.git
D:\X\MyRoot\Z\Demo2.pjx
D:\X\MyRoot\Z\.git
D:\X\MyRoot\solution.xml

This is perfectly well too.

Just call the addin for any pjx?

All you need to do is:
-figure out source control activated
-fire the new addin on every item you think you need the source control root
-store the result

It means nothing to call this several times, on the same directory or on different ones. it just takes time.
