### ISSUE TITLE
Seperate topic-item for classes (VCX)

### ISSUE THREAD

**Issue by HaPe4** [DougHennig/ProjectExplorer#95]
Add a new topic-item for classes (VCX) in treeview. Classes (VCX) are the only files with no master-topic.
When using "All" as filter for treeview i get a very long list although no master-topic is opened.
It will be more productive not using everytime the topic-filter or favorites when many files are modified in a short time.
Take a look to the JPG.
![projectexplorer](https://user-images.githubusercontent.com/29651009/33206144-9c84ad18-d109-11e7-9e00-68a3429dfc51.jpg)

Ok, Rick Borup has this wished before in issue #53

**Comment by lscheffler** [comment]
Hallo Hans-Peter,

das ist schon unter issue #53 erfaßt.

(This is issue #53)

**Comment by HaPe4** [comment]
Hallo Lutz,
das habe ich wohl überlesen :-(
